/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api;

import cloud.artik.api.controllers.*;
import cloud.artik.api.http.client.HttpClient;

public class ARTIKCloudAPIClient {
    /**
     * Singleton access to Subscriptions controller
     * @return	Returns the SubscriptionsController instance 
     */
    public SubscriptionsController getSubscriptions() {
        return SubscriptionsController.getInstance();
    }

    /**
     * Singleton access to DevicesShares controller
     * @return	Returns the DevicesSharesController instance 
     */
    public DevicesSharesController getDevicesShares() {
        return DevicesSharesController.getInstance();
    }

    /**
     * Singleton access to DevicesManagement controller
     * @return	Returns the DevicesManagementController instance 
     */
    public DevicesManagementController getDevicesManagement() {
        return DevicesManagementController.getInstance();
    }

    /**
     * Singleton access to DevicesStatus controller
     * @return	Returns the DevicesStatusController instance 
     */
    public DevicesStatusController getDevicesStatus() {
        return DevicesStatusController.getInstance();
    }

    /**
     * Singleton access to Registrations controller
     * @return	Returns the RegistrationsController instance 
     */
    public RegistrationsController getRegistrations() {
        return RegistrationsController.getInstance();
    }

    /**
     * Singleton access to Tokens controller
     * @return	Returns the TokensController instance 
     */
    public TokensController getTokens() {
        return TokensController.getInstance();
    }

    /**
     * Singleton access to Messages controller
     * @return	Returns the MessagesController instance 
     */
    public MessagesController getMessages() {
        return MessagesController.getInstance();
    }

    /**
     * Singleton access to Rules controller
     * @return	Returns the RulesController instance 
     */
    public RulesController getRules() {
        return RulesController.getInstance();
    }

    /**
     * Singleton access to Export controller
     * @return	Returns the ExportController instance 
     */
    public ExportController getExport() {
        return ExportController.getInstance();
    }

    /**
     * Singleton access to Tags controller
     * @return	Returns the TagsController instance 
     */
    public TagsController getTags() {
        return TagsController.getInstance();
    }

    /**
     * Singleton access to DeviceTypes controller
     * @return	Returns the DeviceTypesController instance 
     */
    public DeviceTypesController getDeviceTypes() {
        return DeviceTypesController.getInstance();
    }

    /**
     * Singleton access to Devices controller
     * @return	Returns the DevicesController instance 
     */
    public DevicesController getDevices() {
        return DevicesController.getInstance();
    }

    /**
     * Singleton access to Users controller
     * @return	Returns the UsersController instance 
     */
    public UsersController getUsers() {
        return UsersController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Get authentication manager
     */
    public OAuthManager auth() {
        return OAuthManager.getInstance();
    }

    /**
     * Default constructor 
     */     
    public ARTIKCloudAPIClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public ARTIKCloudAPIClient(String oAuthClientId, String oAuthRedirectUri) {
        this();
        Configuration.oAuthClientId = oAuthClientId;
        Configuration.oAuthRedirectUri = oAuthRedirectUri;
    }
}