/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Acknowledgement 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5051349668872600889L;
    private String mid;
    private String cid;
    private String message;
    private String code;
    /** GETTER
     * Message ID.
     */
    @JsonGetter("mid")
    public String getMid ( ) { 
        return this.mid;
    }
    
    /** SETTER
     * Message ID.
     */
    @JsonSetter("mid")
    public void setMid (String value) { 
        this.mid = value;
    }
 
    /** GETTER
     * Confirmation ID.
     */
    @JsonGetter("cid")
    public String getCid ( ) { 
        return this.cid;
    }
    
    /** SETTER
     * Confirmation ID.
     */
    @JsonSetter("cid")
    public void setCid (String value) { 
        this.cid = value;
    }
 
    /** GETTER
     * Message.
     */
    @JsonGetter("message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * Message.
     */
    @JsonSetter("message")
    public void setMessage (String value) { 
        this.message = value;
    }
 
    /** GETTER
     * Code
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * Code
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
}
 