/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ActionsBuilder {
    //the instance to build
    private Actions actions;

    /**
     * Default constructor to initialize the instance
     */
    public ActionsBuilder() {
        actions = new Actions();
    }

    /**
     * Holds an array of Actions
     */
    public ActionsBuilder data(ActionArray data) {
        actions.setData(data);
        return this;
    }

    /**
     * Destination Device ID.
     */
    public ActionsBuilder ddid(String ddid) {
        actions.setDdid(ddid);
        return this;
    }

    /**
     * Destination Device ID.
     */
    public ActionsBuilder sdid(String sdid) {
        actions.setSdid(sdid);
        return this;
    }

    /**
     * Timestamp (past, present or future). Defaults to current time if not provided.
     */
    public ActionsBuilder ts(Long ts) {
        actions.setTs(ts);
        return this;
    }

    /**
     * Type - action.
     */
    public ActionsBuilder type(String type) {
        actions.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Actions build() {
        return actions;
    }
}