/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ActionIn 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5433067889160697244L;
    private ActionDetailsArray data;
    private String cid;
    private String ddid;
    private String sdid;
    private Long ts;
    private String type = "action";
    /** GETTER
     * Contains the array of Action Details
     */
    @JsonGetter("data")
    public ActionDetailsArray getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Contains the array of Action Details
     */
    @JsonSetter("data")
    public void setData (ActionDetailsArray value) { 
        this.data = value;
    }
 
    /** GETTER
     * Confirmation ID.
     */
    @JsonGetter("cid")
    public String getCid ( ) { 
        return this.cid;
    }
    
    /** SETTER
     * Confirmation ID.
     */
    @JsonSetter("cid")
    public void setCid (String value) { 
        this.cid = value;
    }
 
    /** GETTER
     * Destination Device ID.
     */
    @JsonGetter("ddid")
    public String getDdid ( ) { 
        return this.ddid;
    }
    
    /** SETTER
     * Destination Device ID.
     */
    @JsonSetter("ddid")
    public void setDdid (String value) { 
        this.ddid = value;
    }
 
    /** GETTER
     * Source Device ID.
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * Source Device ID.
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
    /** GETTER
     * Timestamp (past, present or future). Defaults to current time if not provided.
     */
    @JsonGetter("ts")
    public Long getTs ( ) { 
        return this.ts;
    }
    
    /** SETTER
     * Timestamp (past, present or future). Defaults to current time if not provided.
     */
    @JsonSetter("ts")
    public void setTs (Long value) { 
        this.ts = value;
    }
 
    /** GETTER
     * Type.
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type.
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 