/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Action 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5269122192301010066L;
    private String name;
    private LinkedHashMap<String, Object> parameters;
    /** GETTER
     * Action name.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Action name.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Parameters information
     */
    @JsonGetter("parameters")
    public LinkedHashMap<String, Object> getParameters ( ) { 
        return this.parameters;
    }
    
    /** SETTER
     * Parameters information
     */
    @JsonSetter("parameters")
    public void setParameters (LinkedHashMap<String, Object> value) { 
        this.parameters = value;
    }
 
}
 