/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ActionDetailsBuilder {
    //the instance to build
    private ActionDetails actionDetails;

    /**
     * Default constructor to initialize the instance
     */
    public ActionDetailsBuilder() {
        actionDetails = new ActionDetails();
    }

    /**
     * Parameters.
     */
    public ActionDetailsBuilder parameters(LinkedHashMap<String, Object> parameters) {
        actionDetails.setParameters(parameters);
        return this;
    }

    /**
     * Name.
     */
    public ActionDetailsBuilder name(String name) {
        actionDetails.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ActionDetails build() {
        return actionDetails;
    }
}