/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ActionDetailsArray 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4943925902431765255L;
    private List<ActionDetails> actions;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("actions")
    public List<ActionDetails> getActions ( ) { 
        return this.actions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("actions")
    public void setActions (List<ActionDetails> value) { 
        this.actions = value;
    }
 
}
 