/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class AggregateDataBuilder {
    //the instance to build
    private AggregateData aggregateData;

    /**
     * Default constructor to initialize the instance
     */
    public AggregateDataBuilder() {
        aggregateData = new AggregateData();
    }

    public AggregateDataBuilder count(Long count) {
        aggregateData.setCount(count);
        return this;
    }

    public AggregateDataBuilder max(Double max) {
        aggregateData.setMax(max);
        return this;
    }

    public AggregateDataBuilder mean(Double mean) {
        aggregateData.setMean(mean);
        return this;
    }

    public AggregateDataBuilder min(Double min) {
        aggregateData.setMin(min);
        return this;
    }

    public AggregateDataBuilder sum(Double sum) {
        aggregateData.setSum(sum);
        return this;
    }

    public AggregateDataBuilder variance(Double variance) {
        aggregateData.setVariance(variance);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AggregateData build() {
        return aggregateData;
    }
}