/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AggregatesHistogramData 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5444047357495322266L;
    private Long count;
    private Double max;
    private Double mean;
    private Double min;
    private Double sum;
    private Long ts;
    private Double variance;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("count")
    public Long getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("count")
    public void setCount (Long value) { 
        this.count = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("max")
    public Double getMax ( ) { 
        return this.max;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("max")
    public void setMax (Double value) { 
        this.max = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mean")
    public Double getMean ( ) { 
        return this.mean;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mean")
    public void setMean (Double value) { 
        this.mean = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("min")
    public Double getMin ( ) { 
        return this.min;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("min")
    public void setMin (Double value) { 
        this.min = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sum")
    public Double getSum ( ) { 
        return this.sum;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sum")
    public void setSum (Double value) { 
        this.sum = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ts")
    public Long getTs ( ) { 
        return this.ts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ts")
    public void setTs (Long value) { 
        this.ts = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("variance")
    public Double getVariance ( ) { 
        return this.variance;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("variance")
    public void setVariance (Double value) { 
        this.variance = value;
    }
 
}
 