/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AppProperties 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5708411988754136682L;
    private String properties;
    private String uid;
    private String aid;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("properties")
    public String getProperties ( ) { 
        return this.properties;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("properties")
    public void setProperties (String value) { 
        this.properties = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("aid")
    public String getAid ( ) { 
        return this.aid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("aid")
    public void setAid (String value) { 
        this.aid = value;
    }
 
}
 