/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class CheckTokenMessageBuilder {
    //the instance to build
    private CheckTokenMessage checkTokenMessage;

    /**
     * Default constructor to initialize the instance
     */
    public CheckTokenMessageBuilder() {
        checkTokenMessage = new CheckTokenMessage();
    }

    public CheckTokenMessageBuilder message(String message) {
        checkTokenMessage.setMessage(message);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CheckTokenMessage build() {
        return checkTokenMessage;
    }
}