/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTokenEnvelopeBuilder {
    //the instance to build
    private DeviceTokenEnvelope deviceTokenEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTokenEnvelopeBuilder() {
        deviceTokenEnvelope = new DeviceTokenEnvelope();
    }

    /**
     * Device Token
     */
    public DeviceTokenEnvelopeBuilder data(DeviceToken data) {
        deviceTokenEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceTokenEnvelope build() {
        return deviceTokenEnvelope;
    }
}