/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceEnvelopeBuilder {
    //the instance to build
    private DeviceEnvelope deviceEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceEnvelopeBuilder() {
        deviceEnvelope = new DeviceEnvelope();
    }

    /**
     * Device information.
     */
    public DeviceEnvelopeBuilder data(Device data) {
        deviceEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceEnvelope build() {
        return deviceEnvelope;
    }
}