/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Device 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4841169426220282384L;
    private String id;
    private String uid;
    private String dtid;
    private String name;
    private Integer manifestVersion;
    private String manifestVersionPolicy;
    private Boolean needProviderAuth;
    private LinkedHashMap<String, Object> properties;
    private Long createdOn;
    private Boolean connected;
    private String certificateInfo;
    private String certificateSignature;
    private String eid;
    private LinkedHashMap<String, Object> providerCredentials;
    private Boolean sharedWithOthers;
    private String sharedWithMe;
    /** GETTER
     * Device ID
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Device ID
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * User ID
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * User ID
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * Device Type ID
     */
    @JsonGetter("dtid")
    public String getDtid ( ) { 
        return this.dtid;
    }
    
    /** SETTER
     * Device Type ID
     */
    @JsonSetter("dtid")
    public void setDtid (String value) { 
        this.dtid = value;
    }
 
    /** GETTER
     * Name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Manifest Version
     */
    @JsonGetter("manifestVersion")
    public Integer getManifestVersion ( ) { 
        return this.manifestVersion;
    }
    
    /** SETTER
     * Manifest Version
     */
    @JsonSetter("manifestVersion")
    public void setManifestVersion (Integer value) { 
        this.manifestVersion = value;
    }
 
    /** GETTER
     * Manifest Version Policy (LATEST, DEVICE)
     */
    @JsonGetter("manifestVersionPolicy")
    public String getManifestVersionPolicy ( ) { 
        return this.manifestVersionPolicy;
    }
    
    /** SETTER
     * Manifest Version Policy (LATEST, DEVICE)
     */
    @JsonSetter("manifestVersionPolicy")
    public void setManifestVersionPolicy (String value) { 
        this.manifestVersionPolicy = value;
    }
 
    /** GETTER
     * Needs Provider Authentication
     */
    @JsonGetter("needProviderAuth")
    public Boolean getNeedProviderAuth ( ) { 
        return this.needProviderAuth;
    }
    
    /** SETTER
     * Needs Provider Authentication
     */
    @JsonSetter("needProviderAuth")
    public void setNeedProviderAuth (Boolean value) { 
        this.needProviderAuth = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("properties")
    public LinkedHashMap<String, Object> getProperties ( ) { 
        return this.properties;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("properties")
    public void setProperties (LinkedHashMap<String, Object> value) { 
        this.properties = value;
    }
 
    /** GETTER
     * Created On (milliseconds since epoch)
     */
    @JsonGetter("createdOn")
    public Long getCreatedOn ( ) { 
        return this.createdOn;
    }
    
    /** SETTER
     * Created On (milliseconds since epoch)
     */
    @JsonSetter("createdOn")
    public void setCreatedOn (Long value) { 
        this.createdOn = value;
    }
 
    /** GETTER
     * Is Connected
     */
    @JsonGetter("connected")
    public Boolean getConnected ( ) { 
        return this.connected;
    }
    
    /** SETTER
     * Is Connected
     */
    @JsonSetter("connected")
    public void setConnected (Boolean value) { 
        this.connected = value;
    }
 
    /** GETTER
     * Certificate Info (if any)
     */
    @JsonGetter("certificateInfo")
    public String getCertificateInfo ( ) { 
        return this.certificateInfo;
    }
    
    /** SETTER
     * Certificate Info (if any)
     */
    @JsonSetter("certificateInfo")
    public void setCertificateInfo (String value) { 
        this.certificateInfo = value;
    }
 
    /** GETTER
     * Certificate Signature (if any)
     */
    @JsonGetter("certificateSignature")
    public String getCertificateSignature ( ) { 
        return this.certificateSignature;
    }
    
    /** SETTER
     * Certificate Signature (if any)
     */
    @JsonSetter("certificateSignature")
    public void setCertificateSignature (String value) { 
        this.certificateSignature = value;
    }
 
    /** GETTER
     * External ID (if any)
     */
    @JsonGetter("eid")
    public String getEid ( ) { 
        return this.eid;
    }
    
    /** SETTER
     * External ID (if any)
     */
    @JsonSetter("eid")
    public void setEid (String value) { 
        this.eid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("providerCredentials")
    public LinkedHashMap<String, Object> getProviderCredentials ( ) { 
        return this.providerCredentials;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("providerCredentials")
    public void setProviderCredentials (LinkedHashMap<String, Object> value) { 
        this.providerCredentials = value;
    }
 
    /** GETTER
     * Is shared with other users
     */
    @JsonGetter("sharedWithOthers")
    public Boolean getSharedWithOthers ( ) { 
        return this.sharedWithOthers;
    }
    
    /** SETTER
     * Is shared with other users
     */
    @JsonSetter("sharedWithOthers")
    public void setSharedWithOthers (Boolean value) { 
        this.sharedWithOthers = value;
    }
 
    /** GETTER
     * Share id (if shared with me)
     */
    @JsonGetter("sharedWithMe")
    public String getSharedWithMe ( ) { 
        return this.sharedWithMe;
    }
    
    /** SETTER
     * Share id (if shared with me)
     */
    @JsonSetter("sharedWithMe")
    public void setSharedWithMe (String value) { 
        this.sharedWithMe = value;
    }
 
}
 