/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceSharingIdBuilder {
    //the instance to build
    private DeviceSharingId deviceSharingId;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceSharingIdBuilder() {
        deviceSharingId = new DeviceSharingId();
    }

    /**
     * Share ID
     */
    public DeviceSharingIdBuilder shareId(String shareId) {
        deviceSharingId.setShareId(shareId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceSharingId build() {
        return deviceSharingId;
    }
}