/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceStatus 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5219784321051667430L;
    private DeviceStatusData data;
    private String did;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public DeviceStatusData getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (DeviceStatusData value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("did")
    public String getDid ( ) { 
        return this.did;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("did")
    public void setDid (String value) { 
        this.did = value;
    }
 
}
 