/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceType 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5540407650574307188L;
    private String id;
    private String uniqueName;
    private Integer latestVersion;
    private Long lastUpdated;
    private String name;
    private String description;
    private String uid;
    private String oid;
    private Boolean hasCloudConnector;
    private Boolean approved;
    private Boolean published;
    private Boolean mprotected;
    private Boolean inStore;
    private Boolean ownedByCurrentUser;
    private List<Tag> tags;
    private Boolean rsp;
    private String issuerDn;
    private String vid;
    /** GETTER
     * Device Type ID.
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Device Type ID.
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * Unique Name.
     */
    @JsonGetter("uniqueName")
    public String getUniqueName ( ) { 
        return this.uniqueName;
    }
    
    /** SETTER
     * Unique Name.
     */
    @JsonSetter("uniqueName")
    public void setUniqueName (String value) { 
        this.uniqueName = value;
    }
 
    /** GETTER
     * Latest Manifest version.
     */
    @JsonGetter("latestVersion")
    public Integer getLatestVersion ( ) { 
        return this.latestVersion;
    }
    
    /** SETTER
     * Latest Manifest version.
     */
    @JsonSetter("latestVersion")
    public void setLatestVersion (Integer value) { 
        this.latestVersion = value;
    }
 
    /** GETTER
     * Last Updated Timestamp.
     */
    @JsonGetter("lastUpdated")
    public Long getLastUpdated ( ) { 
        return this.lastUpdated;
    }
    
    /** SETTER
     * Last Updated Timestamp.
     */
    @JsonSetter("lastUpdated")
    public void setLastUpdated (Long value) { 
        this.lastUpdated = value;
    }
 
    /** GETTER
     * Name.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Description.
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * Description.
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * User ID.
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * User ID.
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * Organization ID.
     */
    @JsonGetter("oid")
    public String getOid ( ) { 
        return this.oid;
    }
    
    /** SETTER
     * Organization ID.
     */
    @JsonSetter("oid")
    public void setOid (String value) { 
        this.oid = value;
    }
 
    /** GETTER
     * Uses Cloud Connectors SDK
     */
    @JsonGetter("hasCloudConnector")
    public Boolean getHasCloudConnector ( ) { 
        return this.hasCloudConnector;
    }
    
    /** SETTER
     * Uses Cloud Connectors SDK
     */
    @JsonSetter("hasCloudConnector")
    public void setHasCloudConnector (Boolean value) { 
        this.hasCloudConnector = value;
    }
 
    /** GETTER
     * Approval status.
     */
    @JsonGetter("approved")
    public Boolean getApproved ( ) { 
        return this.approved;
    }
    
    /** SETTER
     * Approval status.
     */
    @JsonSetter("approved")
    public void setApproved (Boolean value) { 
        this.approved = value;
    }
 
    /** GETTER
     * Published status.
     */
    @JsonGetter("published")
    public Boolean getPublished ( ) { 
        return this.published;
    }
    
    /** SETTER
     * Published status.
     */
    @JsonSetter("published")
    public void setPublished (Boolean value) { 
        this.published = value;
    }
 
    /** GETTER
     * Protected status.
     */
    @JsonGetter("protected")
    public Boolean getProtected ( ) { 
        return this.mprotected;
    }
    
    /** SETTER
     * Protected status.
     */
    @JsonSetter("protected")
    public void setProtected (Boolean value) { 
        this.mprotected = value;
    }
 
    /** GETTER
     * In Store.
     */
    @JsonGetter("inStore")
    public Boolean getInStore ( ) { 
        return this.inStore;
    }
    
    /** SETTER
     * In Store.
     */
    @JsonSetter("inStore")
    public void setInStore (Boolean value) { 
        this.inStore = value;
    }
 
    /** GETTER
     * Does the current user own a device of this device type
     */
    @JsonGetter("ownedByCurrentUser")
    public Boolean getOwnedByCurrentUser ( ) { 
        return this.ownedByCurrentUser;
    }
    
    /** SETTER
     * Does the current user own a device of this device type
     */
    @JsonSetter("ownedByCurrentUser")
    public void setOwnedByCurrentUser (Boolean value) { 
        this.ownedByCurrentUser = value;
    }
 
    /** GETTER
     * Tags
     */
    @JsonGetter("tags")
    public List<Tag> getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * Tags
     */
    @JsonSetter("tags")
    public void setTags (List<Tag> value) { 
        this.tags = value;
    }
 
    /** GETTER
     * Require Secure Device Registration (SDR) Protocol.
     */
    @JsonGetter("rsp")
    public Boolean getRsp ( ) { 
        return this.rsp;
    }
    
    /** SETTER
     * Require Secure Device Registration (SDR) Protocol.
     */
    @JsonSetter("rsp")
    public void setRsp (Boolean value) { 
        this.rsp = value;
    }
 
    /** GETTER
     * Issuer Distinguished Name (Used in SDR)
     */
    @JsonGetter("issuerDn")
    public String getIssuerDn ( ) { 
        return this.issuerDn;
    }
    
    /** SETTER
     * Issuer Distinguished Name (Used in SDR)
     */
    @JsonSetter("issuerDn")
    public void setIssuerDn (String value) { 
        this.issuerDn = value;
    }
 
    /** GETTER
     * Vendor ID. (Used in SDR)
     */
    @JsonGetter("vid")
    public String getVid ( ) { 
        return this.vid;
    }
    
    /** SETTER
     * Vendor ID. (Used in SDR)
     */
    @JsonSetter("vid")
    public void setVid (String value) { 
        this.vid = value;
    }
 
}
 