/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceStatusPutDataBuilder {
    //the instance to build
    private DeviceStatusPutData deviceStatusPutData;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceStatusPutDataBuilder() {
        deviceStatusPutData = new DeviceStatusPutData();
    }

    public DeviceStatusPutDataBuilder availability(String availability) {
        deviceStatusPutData.setAvailability(availability);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceStatusPutData build() {
        return deviceStatusPutData;
    }
}