/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceSharingArrayBuilder {
    //the instance to build
    private DeviceSharingArray deviceSharingArray;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceSharingArrayBuilder() {
        deviceSharingArray = new DeviceSharingArray();
    }

    public DeviceSharingArrayBuilder shares(List<DeviceSharing> shares) {
        deviceSharingArray.setShares(shares);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceSharingArray build() {
        return deviceSharingArray;
    }
}