/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceRegConfirmUserResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5215243340535367568L;
    private String rid;
    /** GETTER
     * The registration request id.
     */
    @JsonGetter("rid")
    public String getRid ( ) { 
        return this.rid;
    }
    
    /** SETTER
     * The registration request id.
     */
    @JsonSetter("rid")
    public void setRid (String value) { 
        this.rid = value;
    }
 
}
 