/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTokenBuilder {
    //the instance to build
    private DeviceToken deviceToken;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTokenBuilder() {
        deviceToken = new DeviceToken();
    }

    public DeviceTokenBuilder accessToken(String accessToken) {
        deviceToken.setAccessToken(accessToken);
        return this;
    }

    public DeviceTokenBuilder uid(String uid) {
        deviceToken.setUid(uid);
        return this;
    }

    public DeviceTokenBuilder did(String did) {
        deviceToken.setDid(did);
        return this;
    }

    public DeviceTokenBuilder cid(String cid) {
        deviceToken.setCid(cid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceToken build() {
        return deviceToken;
    }
}