/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTypeInfoEnvelopeBuilder {
    //the instance to build
    private DeviceTypeInfoEnvelope deviceTypeInfoEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTypeInfoEnvelopeBuilder() {
        deviceTypeInfoEnvelope = new DeviceTypeInfoEnvelope();
    }

    public DeviceTypeInfoEnvelopeBuilder data(DeviceTypeInfo data) {
        deviceTypeInfoEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceTypeInfoEnvelope build() {
        return deviceTypeInfoEnvelope;
    }
}