/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTypeEnvelopeBuilder {
    //the instance to build
    private DeviceTypeEnvelope deviceTypeEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTypeEnvelopeBuilder() {
        deviceTypeEnvelope = new DeviceTypeEnvelope();
    }

    /**
     * Device Type Information
     */
    public DeviceTypeEnvelopeBuilder data(DeviceType data) {
        deviceTypeEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceTypeEnvelope build() {
        return deviceTypeEnvelope;
    }
}