/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceTypeArray 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5020520892436609093L;
    private List<DeviceType> deviceTypes;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceTypes")
    public List<DeviceType> getDeviceTypes ( ) { 
        return this.deviceTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceTypes")
    public void setDeviceTypes (List<DeviceType> value) { 
        this.deviceTypes = value;
    }
 
}
 