/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTypesInfoBuilder {
    //the instance to build
    private DeviceTypesInfo deviceTypesInfo;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTypesInfoBuilder() {
        deviceTypesInfo = new DeviceTypesInfo();
    }

    /**
     * Device Properties Enabled
     */
    public DeviceTypesInfoBuilder devicePropertiesEnabled(Boolean devicePropertiesEnabled) {
        deviceTypesInfo.setDevicePropertiesEnabled(devicePropertiesEnabled);
        return this;
    }

    /**
     * Pmax value
     */
    public DeviceTypesInfoBuilder pmax(Integer pmax) {
        deviceTypesInfo.setPmax(pmax);
        return this;
    }

    /**
     * Modified on
     */
    public DeviceTypesInfoBuilder modifiedOn(Long modifiedOn) {
        deviceTypesInfo.setModifiedOn(modifiedOn);
        return this;
    }

    /**
     * Device Type ID
     */
    public DeviceTypesInfoBuilder dtid(String dtid) {
        deviceTypesInfo.setDtid(dtid);
        return this;
    }

    /**
     * Pmin value
     */
    public DeviceTypesInfoBuilder pmin(Integer pmin) {
        deviceTypesInfo.setPmin(pmin);
        return this;
    }

    /**
     * Default task expiration time in seconds
     */
    public DeviceTypesInfoBuilder taskExpiresAfter(Integer taskExpiresAfter) {
        deviceTypesInfo.setTaskExpiresAfter(taskExpiresAfter);
        return this;
    }

    /**
     * Created on
     */
    public DeviceTypesInfoBuilder createdOn(Long createdOn) {
        deviceTypesInfo.setCreatedOn(createdOn);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceTypesInfo build() {
        return deviceTypesInfo;
    }
}