/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DevicesEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5025691984509990642L;
    private int total;
    private int count;
    private int offset;
    private DeviceArray data;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("total")
    public int getTotal ( ) { 
        return this.total;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("total")
    public void setTotal (int value) { 
        this.total = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("count")
    public int getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("count")
    public void setCount (int value) { 
        this.count = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("offset")
    public int getOffset ( ) { 
        return this.offset;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("offset")
    public void setOffset (int value) { 
        this.offset = value;
    }
 
    /** GETTER
     * Holds an array of Devices
     */
    @JsonGetter("data")
    public DeviceArray getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Holds an array of Devices
     */
    @JsonSetter("data")
    public void setData (DeviceArray value) { 
        this.data = value;
    }
 
}
 