/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceStatusBuilder {
    //the instance to build
    private DeviceStatus deviceStatus;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceStatusBuilder() {
        deviceStatus = new DeviceStatus();
    }

    public DeviceStatusBuilder data(DeviceStatusData data) {
        deviceStatus.setData(data);
        return this;
    }

    public DeviceStatusBuilder did(String did) {
        deviceStatus.setDid(did);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceStatus build() {
        return deviceStatus;
    }
}