/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTypeInfoBuilder {
    //the instance to build
    private DeviceTypeInfo deviceTypeInfo;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTypeInfoBuilder() {
        deviceTypeInfo = new DeviceTypeInfo();
    }

    /**
     * Device Properties Enabled
     */
    public DeviceTypeInfoBuilder devicePropertiesEnabled(Boolean devicePropertiesEnabled) {
        deviceTypeInfo.setDevicePropertiesEnabled(devicePropertiesEnabled);
        return this;
    }

    /**
     * Pmax value
     */
    public DeviceTypeInfoBuilder pmax(Integer pmax) {
        deviceTypeInfo.setPmax(pmax);
        return this;
    }

    /**
     * Modified on
     */
    public DeviceTypeInfoBuilder modifiedOn(Long modifiedOn) {
        deviceTypeInfo.setModifiedOn(modifiedOn);
        return this;
    }

    /**
     * Device Type ID
     */
    public DeviceTypeInfoBuilder dtid(String dtid) {
        deviceTypeInfo.setDtid(dtid);
        return this;
    }

    /**
     * Pmin value
     */
    public DeviceTypeInfoBuilder pmin(Integer pmin) {
        deviceTypeInfo.setPmin(pmin);
        return this;
    }

    /**
     * Default task expiration time in seconds
     */
    public DeviceTypeInfoBuilder taskExpiresAfter(Integer taskExpiresAfter) {
        deviceTypeInfo.setTaskExpiresAfter(taskExpiresAfter);
        return this;
    }

    /**
     * Created on
     */
    public DeviceTypeInfoBuilder createdOn(Long createdOn) {
        deviceTypeInfo.setCreatedOn(createdOn);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceTypeInfo build() {
        return deviceTypeInfo;
    }
}