/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceRegConfirmUserRequestBuilder {
    //the instance to build
    private DeviceRegConfirmUserRequest deviceRegConfirmUserRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceRegConfirmUserRequestBuilder() {
        deviceRegConfirmUserRequest = new DeviceRegConfirmUserRequest();
    }

    /**
     * Device ID. Optional if deviceName is present
     */
    public DeviceRegConfirmUserRequestBuilder deviceId(String deviceId) {
        deviceRegConfirmUserRequest.setDeviceId(deviceId);
        return this;
    }

    /**
     * Device Name. Optional if deviceId is present
     */
    public DeviceRegConfirmUserRequestBuilder deviceName(String deviceName) {
        deviceRegConfirmUserRequest.setDeviceName(deviceName);
        return this;
    }

    /**
     * Pin obtained in the registrations call.
     */
    public DeviceRegConfirmUserRequestBuilder pin(String pin) {
        deviceRegConfirmUserRequest.setPin(pin);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceRegConfirmUserRequest build() {
        return deviceRegConfirmUserRequest;
    }
}