/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTaskUpdateRequestBuilder {
    //the instance to build
    private DeviceTaskUpdateRequest deviceTaskUpdateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTaskUpdateRequestBuilder() {
        deviceTaskUpdateRequest = new DeviceTaskUpdateRequest();
    }

    /**
     * Status
     */
    public DeviceTaskUpdateRequestBuilder status(String status) {
        deviceTaskUpdateRequest.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceTaskUpdateRequest build() {
        return deviceTaskUpdateRequest;
    }
}