/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceStatusPut 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4676293296472672610L;
    private DeviceStatusPutData data;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public DeviceStatusPutData getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (DeviceStatusPutData value) { 
        this.data = value;
    }
 
}
 