/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceSharingArray 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5677339164971194870L;
    private List<DeviceSharing> shares;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shares")
    public List<DeviceSharing> getShares ( ) { 
        return this.shares;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shares")
    public void setShares (List<DeviceSharing> value) { 
        this.shares = value;
    }
 
}
 