/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceTypeEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4856918195168520398L;
    private DeviceType data;
    /** GETTER
     * Device Type Information
     */
    @JsonGetter("data")
    public DeviceType getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Device Type Information
     */
    @JsonSetter("data")
    public void setData (DeviceType value) { 
        this.data = value;
    }
 
}
 