/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceTypesEnvelopeBuilder {
    //the instance to build
    private DeviceTypesEnvelope deviceTypesEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTypesEnvelopeBuilder() {
        deviceTypesEnvelope = new DeviceTypesEnvelope();
    }

    public DeviceTypesEnvelopeBuilder total(int total) {
        deviceTypesEnvelope.setTotal(total);
        return this;
    }

    public DeviceTypesEnvelopeBuilder count(int count) {
        deviceTypesEnvelope.setCount(count);
        return this;
    }

    public DeviceTypesEnvelopeBuilder offset(int offset) {
        deviceTypesEnvelope.setOffset(offset);
        return this;
    }

    /**
     * Holds an array of DeviceTypes
     */
    public DeviceTypesEnvelopeBuilder data(DeviceTypeArray data) {
        deviceTypesEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceTypesEnvelope build() {
        return deviceTypesEnvelope;
    }
}