/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceStatusBatchBuilder {
    //the instance to build
    private DeviceStatusBatch deviceStatusBatch;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceStatusBatchBuilder() {
        deviceStatusBatch = new DeviceStatusBatch();
    }

    public DeviceStatusBatchBuilder total(Integer total) {
        deviceStatusBatch.setTotal(total);
        return this;
    }

    public DeviceStatusBatchBuilder offset(Integer offset) {
        deviceStatusBatch.setOffset(offset);
        return this;
    }

    public DeviceStatusBatchBuilder data(List<DeviceStatus> data) {
        deviceStatusBatch.setData(data);
        return this;
    }

    public DeviceStatusBatchBuilder count(Integer count) {
        deviceStatusBatch.setCount(count);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceStatusBatch build() {
        return deviceStatusBatch;
    }
}