/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceSharingId 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5556012213532472322L;
    private String shareId;
    /** GETTER
     * Share ID
     */
    @JsonGetter("shareId")
    public String getShareId ( ) { 
        return this.shareId;
    }
    
    /** SETTER
     * Share ID
     */
    @JsonSetter("shareId")
    public void setShareId (String value) { 
        this.shareId = value;
    }
 
}
 