/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceSharing 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4636961501265946823L;
    private String id;
    private String email;
    private String status;
    private Long sharedOn;
    /** GETTER
     * Share ID
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Share ID
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * Email
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * Email
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
    /** GETTER
     * Status
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * Status
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * Shared on
     */
    @JsonGetter("sharedOn")
    public Long getSharedOn ( ) { 
        return this.sharedOn;
    }
    
    /** SETTER
     * Shared on
     */
    @JsonSetter("sharedOn")
    public void setSharedOn (Long value) { 
        this.sharedOn = value;
    }
 
}
 