/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceStatusDataBuilder {
    //the instance to build
    private DeviceStatusData deviceStatusData;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceStatusDataBuilder() {
        deviceStatusData = new DeviceStatusData();
    }

    public DeviceStatusDataBuilder lastTimeOnline(Long lastTimeOnline) {
        deviceStatusData.setLastTimeOnline(lastTimeOnline);
        return this;
    }

    public DeviceStatusDataBuilder lastActionTs(Long lastActionTs) {
        deviceStatusData.setLastActionTs(lastActionTs);
        return this;
    }

    public DeviceStatusDataBuilder lastMessageTs(Long lastMessageTs) {
        deviceStatusData.setLastMessageTs(lastMessageTs);
        return this;
    }

    public DeviceStatusDataBuilder availability(String availability) {
        deviceStatusData.setAvailability(availability);
        return this;
    }

    public DeviceStatusDataBuilder snapshot(LinkedHashMap<String, Object> snapshot) {
        deviceStatusData.setSnapshot(snapshot);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceStatusData build() {
        return deviceStatusData;
    }
}