/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceArray 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5511921192412122114L;
    private List<Device> devices;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devices")
    public List<Device> getDevices ( ) { 
        return this.devices;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devices")
    public void setDevices (List<Device> value) { 
        this.devices = value;
    }
 
}
 