/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class DeviceArrayBuilder {
    //the instance to build
    private DeviceArray deviceArray;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceArrayBuilder() {
        deviceArray = new DeviceArray();
    }

    public DeviceArrayBuilder devices(List<Device> devices) {
        deviceArray.setDevices(devices);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceArray build() {
        return deviceArray;
    }
}