/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceRegCompleteRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4900064266297441900L;
    private String nonce;
    /** GETTER
     * Nonce obtained from the initial registration request.
     */
    @JsonGetter("nonce")
    public String getNonce ( ) { 
        return this.nonce;
    }
    
    /** SETTER
     * Nonce obtained from the initial registration request.
     */
    @JsonSetter("nonce")
    public void setNonce (String value) { 
        this.nonce = value;
    }
 
}
 