/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum EntityTypeEnum {
    TAG, //TODO: Write general description for this element
    APPLICATION, //TODO: Write general description for this element
    DEVICE_TYPE; //TODO: Write general description for this element

    private static TreeMap<String, EntityTypeEnum> valueMap = new TreeMap<String, EntityTypeEnum>();
    private String value;

    static {
        TAG.value = "TAG";
        APPLICATION.value = "APPLICATION";
        DEVICE_TYPE.value = "DEVICE_TYPE";

        valueMap.put("TAG", TAG);
        valueMap.put("APPLICATION", APPLICATION);
        valueMap.put("DEVICE_TYPE", DEVICE_TYPE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static EntityTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EntityTypeEnum values to list of string values
     * @param toConvert The list of EntityTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<EntityTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (EntityTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 