/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ErrorEnvelopeBuilder {
    //the instance to build
    private ErrorEnvelope errorEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public ErrorEnvelopeBuilder() {
        errorEnvelope = new ErrorEnvelope();
    }

    /**
     * Error Data
     */
    public ErrorEnvelopeBuilder error(WebSocketError error) {
        errorEnvelope.setError(error);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ErrorEnvelope build() {
        return errorEnvelope;
    }
}