/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class EventFeedDataBuilder {
    //the instance to build
    private EventFeedData eventFeedData;

    /**
     * Default constructor to initialize the instance
     */
    public EventFeedDataBuilder() {
        eventFeedData = new EventFeedData();
    }

    /**
     * Event
     */
    public EventFeedDataBuilder event(String event) {
        eventFeedData.setEvent(event);
        return this;
    }

    /**
     * Timestamp
     */
    public EventFeedDataBuilder ts(Long ts) {
        eventFeedData.setTs(ts);
        return this;
    }

    /**
     * Message Payload
     */
    public EventFeedDataBuilder data(LinkedHashMap<String, Object> data) {
        eventFeedData.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EventFeedData build() {
        return eventFeedData;
    }
}