/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ExportNormalizedMessagesResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5215267396590316216L;
    private Boolean csvHeaders;
    private Long endDate;
    private String exportId;
    private String format;
    private String order;
    private String sdid;
    private String sdids;
    private Long startDate;
    private String stdids;
    private String trialId;
    private String uid;
    private String uids;
    private String url;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("csvHeaders")
    public Boolean getCsvHeaders ( ) { 
        return this.csvHeaders;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("csvHeaders")
    public void setCsvHeaders (Boolean value) { 
        this.csvHeaders = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("endDate")
    public Long getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("endDate")
    public void setEndDate (Long value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exportId")
    public String getExportId ( ) { 
        return this.exportId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exportId")
    public void setExportId (String value) { 
        this.exportId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("format")
    public String getFormat ( ) { 
        return this.format;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("format")
    public void setFormat (String value) { 
        this.format = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("order")
    public String getOrder ( ) { 
        return this.order;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("order")
    public void setOrder (String value) { 
        this.order = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdids")
    public String getSdids ( ) { 
        return this.sdids;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdids")
    public void setSdids (String value) { 
        this.sdids = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("startDate")
    public Long getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("startDate")
    public void setStartDate (Long value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("stdids")
    public String getStdids ( ) { 
        return this.stdids;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("stdids")
    public void setStdids (String value) { 
        this.stdids = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trialId")
    public String getTrialId ( ) { 
        return this.trialId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trialId")
    public void setTrialId (String value) { 
        this.trialId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("uids")
    public String getUids ( ) { 
        return this.uids;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("uids")
    public void setUids (String value) { 
        this.uids = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
}
 