/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ExportRequestInfoBuilder {
    //the instance to build
    private ExportRequestInfo exportRequestInfo;

    /**
     * Default constructor to initialize the instance
     */
    public ExportRequestInfoBuilder() {
        exportRequestInfo = new ExportRequestInfo();
    }

    /**
     * Add header to csv format
     */
    public ExportRequestInfoBuilder csvHeaders(Boolean csvHeaders) {
        exportRequestInfo.setCsvHeaders(csvHeaders);
        return this;
    }

    /**
     * Timestamp of latest message (in milliseconds since epoch).
     */
    public ExportRequestInfoBuilder endDate(Long endDate) {
        exportRequestInfo.setEndDate(endDate);
        return this;
    }

    /**
     * Format of the export.
     */
    public ExportRequestInfoBuilder format(String format) {
        exportRequestInfo.setFormat(format);
        return this;
    }

    /**
     * Ascending or descending sort order.
     */
    public ExportRequestInfoBuilder order(String order) {
        exportRequestInfo.setOrder(order);
        return this;
    }

    /**
     * Source Device IDs being searched for messages (Comma-separated for multiple Device IDs).
     */
    public ExportRequestInfoBuilder sdids(String sdids) {
        exportRequestInfo.setSdids(sdids);
        return this;
    }

    /**
     * Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs).
     */
    public ExportRequestInfoBuilder sdtids(String sdtids) {
        exportRequestInfo.setSdtids(sdtids);
        return this;
    }

    /**
     * Timestamp of earliest message (in milliseconds since epoch).
     */
    public ExportRequestInfoBuilder startDate(Long startDate) {
        exportRequestInfo.setStartDate(startDate);
        return this;
    }

    /**
     * Trial ID being searched for messages.
     */
    public ExportRequestInfoBuilder trialId(String trialId) {
        exportRequestInfo.setTrialId(trialId);
        return this;
    }

    /**
     * Owner's user IDs being searched for messages (Comma-separated for multiple User IDs).
     */
    public ExportRequestInfoBuilder uids(String uids) {
        exportRequestInfo.setUids(uids);
        return this;
    }

    /**
     * URL added to successful email message.
     */
    public ExportRequestInfoBuilder url(String url) {
        exportRequestInfo.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExportRequestInfo build() {
        return exportRequestInfo;
    }
}