/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ExportData 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4693930902244646027L;
    private Long expirationDate;
    private String exportId;
    private Long fileSize;
    private String md5;
    private ExportRequest request;
    private String status;
    private Long totalMessages;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expirationDate")
    public Long getExpirationDate ( ) { 
        return this.expirationDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expirationDate")
    public void setExpirationDate (Long value) { 
        this.expirationDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exportId")
    public String getExportId ( ) { 
        return this.exportId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exportId")
    public void setExportId (String value) { 
        this.exportId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fileSize")
    public Long getFileSize ( ) { 
        return this.fileSize;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fileSize")
    public void setFileSize (Long value) { 
        this.fileSize = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("md5")
    public String getMd5 ( ) { 
        return this.md5;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("md5")
    public void setMd5 (String value) { 
        this.md5 = value;
    }
 
    /** GETTER
     * Export Request.
     */
    @JsonGetter("request")
    public ExportRequest getRequest ( ) { 
        return this.request;
    }
    
    /** SETTER
     * Export Request.
     */
    @JsonSetter("request")
    public void setRequest (ExportRequest value) { 
        this.request = value;
    }
 
    /** GETTER
     * Export status
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * Export status
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("totalMessages")
    public Long getTotalMessages ( ) { 
        return this.totalMessages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("totalMessages")
    public void setTotalMessages (Long value) { 
        this.totalMessages = value;
    }
 
}
 