/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ExportHistoryResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5008318632458001625L;
    private Long count;
    private ExportDataArray data;
    private Long offset;
    private Long total;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("count")
    public Long getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("count")
    public void setCount (Long value) { 
        this.count = value;
    }
 
    /** GETTER
     * Export Data Array.
     */
    @JsonGetter("data")
    public ExportDataArray getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Export Data Array.
     */
    @JsonSetter("data")
    public void setData (ExportDataArray value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("offset")
    public Long getOffset ( ) { 
        return this.offset;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("offset")
    public void setOffset (Long value) { 
        this.offset = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("total")
    public Long getTotal ( ) { 
        return this.total;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("total")
    public void setTotal (Long value) { 
        this.total = value;
    }
 
}
 