/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ExportRequestResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5008180123696482288L;
    private ExportRequestData data;
    /** GETTER
     * Export Request Data.
     */
    @JsonGetter("data")
    public ExportRequestData getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Export Request Data.
     */
    @JsonSetter("data")
    public void setData (ExportRequestData value) { 
        this.data = value;
    }
 
}
 