/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ExportRequestDataBuilder {
    //the instance to build
    private ExportRequestData exportRequestData;

    /**
     * Default constructor to initialize the instance
     */
    public ExportRequestDataBuilder() {
        exportRequestData = new ExportRequestData();
    }

    /**
     * Add header to csv format
     */
    public ExportRequestDataBuilder csvHeaders(Boolean csvHeaders) {
        exportRequestData.setCsvHeaders(csvHeaders);
        return this;
    }

    /**
     * Timestamp of latest message (in milliseconds since epoch).
     */
    public ExportRequestDataBuilder endDate(Long endDate) {
        exportRequestData.setEndDate(endDate);
        return this;
    }

    /**
     * Returned Export ID that should be used to check status and get the export result.
     */
    public ExportRequestDataBuilder exportId(String exportId) {
        exportRequestData.setExportId(exportId);
        return this;
    }

    /**
     * Format of the export.
     */
    public ExportRequestDataBuilder format(String format) {
        exportRequestData.setFormat(format);
        return this;
    }

    /**
     * Ascending or descending sort order.
     */
    public ExportRequestDataBuilder order(String order) {
        exportRequestData.setOrder(order);
        return this;
    }

    /**
     * Source Device IDs being searched for messages (Comma-separated for multiple Device IDs).
     */
    public ExportRequestDataBuilder sdids(String sdids) {
        exportRequestData.setSdids(sdids);
        return this;
    }

    /**
     * Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs).
     */
    public ExportRequestDataBuilder sdtids(String sdtids) {
        exportRequestData.setSdtids(sdtids);
        return this;
    }

    /**
     * Timestamp of earliest message (in milliseconds since epoch).
     */
    public ExportRequestDataBuilder startDate(Long startDate) {
        exportRequestData.setStartDate(startDate);
        return this;
    }

    /**
     * Trial ID being searched for messages.
     */
    public ExportRequestDataBuilder trialId(String trialId) {
        exportRequestData.setTrialId(trialId);
        return this;
    }

    /**
     * Owner's user IDs being searched for messages (Comma-separated for multiple User IDs).
     */
    public ExportRequestDataBuilder uids(String uids) {
        exportRequestData.setUids(uids);
        return this;
    }

    /**
     * URL added to successful email message.
     */
    public ExportRequestDataBuilder url(String url) {
        exportRequestData.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExportRequestData build() {
        return exportRequestData;
    }
}