/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ExportRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4847730261871686310L;
    private Long endDate;
    private String format;
    private String order;
    private String sdids;
    private String sdtids;
    private Long startDate;
    private String trialId;
    private String uids;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("endDate")
    public Long getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("endDate")
    public void setEndDate (Long value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("format")
    public String getFormat ( ) { 
        return this.format;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("format")
    public void setFormat (String value) { 
        this.format = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("order")
    public String getOrder ( ) { 
        return this.order;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("order")
    public void setOrder (String value) { 
        this.order = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdids")
    public String getSdids ( ) { 
        return this.sdids;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdids")
    public void setSdids (String value) { 
        this.sdids = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdtids")
    public String getSdtids ( ) { 
        return this.sdtids;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdtids")
    public void setSdtids (String value) { 
        this.sdtids = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("startDate")
    public Long getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("startDate")
    public void setStartDate (Long value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trialId")
    public String getTrialId ( ) { 
        return this.trialId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trialId")
    public void setTrialId (String value) { 
        this.trialId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("uids")
    public String getUids ( ) { 
        return this.uids;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("uids")
    public void setUids (String value) { 
        this.uids = value;
    }
 
}
 