/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ExportDataBuilder {
    //the instance to build
    private ExportData exportData;

    /**
     * Default constructor to initialize the instance
     */
    public ExportDataBuilder() {
        exportData = new ExportData();
    }

    public ExportDataBuilder expirationDate(Long expirationDate) {
        exportData.setExpirationDate(expirationDate);
        return this;
    }

    public ExportDataBuilder exportId(String exportId) {
        exportData.setExportId(exportId);
        return this;
    }

    public ExportDataBuilder fileSize(Long fileSize) {
        exportData.setFileSize(fileSize);
        return this;
    }

    public ExportDataBuilder md5(String md5) {
        exportData.setMd5(md5);
        return this;
    }

    /**
     * Export Request.
     */
    public ExportDataBuilder request(ExportRequest request) {
        exportData.setRequest(request);
        return this;
    }

    /**
     * Export status
     */
    public ExportDataBuilder status(String status) {
        exportData.setStatus(status);
        return this;
    }

    public ExportDataBuilder totalMessages(Long totalMessages) {
        exportData.setTotalMessages(totalMessages);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExportData build() {
        return exportData;
    }
}