/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ExportRequestData 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5121743799440177325L;
    private Boolean csvHeaders;
    private Long endDate;
    private String exportId;
    private String format;
    private String order;
    private String sdids;
    private String sdtids;
    private Long startDate;
    private String trialId;
    private String uids;
    private String url;
    /** GETTER
     * Add header to csv format
     */
    @JsonGetter("csvHeaders")
    public Boolean getCsvHeaders ( ) { 
        return this.csvHeaders;
    }
    
    /** SETTER
     * Add header to csv format
     */
    @JsonSetter("csvHeaders")
    public void setCsvHeaders (Boolean value) { 
        this.csvHeaders = value;
    }
 
    /** GETTER
     * Timestamp of latest message (in milliseconds since epoch).
     */
    @JsonGetter("endDate")
    public Long getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * Timestamp of latest message (in milliseconds since epoch).
     */
    @JsonSetter("endDate")
    public void setEndDate (Long value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * Returned Export ID that should be used to check status and get the export result.
     */
    @JsonGetter("exportId")
    public String getExportId ( ) { 
        return this.exportId;
    }
    
    /** SETTER
     * Returned Export ID that should be used to check status and get the export result.
     */
    @JsonSetter("exportId")
    public void setExportId (String value) { 
        this.exportId = value;
    }
 
    /** GETTER
     * Format of the export.
     */
    @JsonGetter("format")
    public String getFormat ( ) { 
        return this.format;
    }
    
    /** SETTER
     * Format of the export.
     */
    @JsonSetter("format")
    public void setFormat (String value) { 
        this.format = value;
    }
 
    /** GETTER
     * Ascending or descending sort order.
     */
    @JsonGetter("order")
    public String getOrder ( ) { 
        return this.order;
    }
    
    /** SETTER
     * Ascending or descending sort order.
     */
    @JsonSetter("order")
    public void setOrder (String value) { 
        this.order = value;
    }
 
    /** GETTER
     * Source Device IDs being searched for messages (Comma-separated for multiple Device IDs).
     */
    @JsonGetter("sdids")
    public String getSdids ( ) { 
        return this.sdids;
    }
    
    /** SETTER
     * Source Device IDs being searched for messages (Comma-separated for multiple Device IDs).
     */
    @JsonSetter("sdids")
    public void setSdids (String value) { 
        this.sdids = value;
    }
 
    /** GETTER
     * Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs).
     */
    @JsonGetter("sdtids")
    public String getSdtids ( ) { 
        return this.sdtids;
    }
    
    /** SETTER
     * Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs).
     */
    @JsonSetter("sdtids")
    public void setSdtids (String value) { 
        this.sdtids = value;
    }
 
    /** GETTER
     * Timestamp of earliest message (in milliseconds since epoch).
     */
    @JsonGetter("startDate")
    public Long getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * Timestamp of earliest message (in milliseconds since epoch).
     */
    @JsonSetter("startDate")
    public void setStartDate (Long value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * Trial ID being searched for messages.
     */
    @JsonGetter("trialId")
    public String getTrialId ( ) { 
        return this.trialId;
    }
    
    /** SETTER
     * Trial ID being searched for messages.
     */
    @JsonSetter("trialId")
    public void setTrialId (String value) { 
        this.trialId = value;
    }
 
    /** GETTER
     * Owner's user IDs being searched for messages (Comma-separated for multiple User IDs).
     */
    @JsonGetter("uids")
    public String getUids ( ) { 
        return this.uids;
    }
    
    /** SETTER
     * Owner's user IDs being searched for messages (Comma-separated for multiple User IDs).
     */
    @JsonSetter("uids")
    public void setUids (String value) { 
        this.uids = value;
    }
 
    /** GETTER
     * URL added to successful email message.
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * URL added to successful email message.
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
}
 