/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ExportRequestBuilder {
    //the instance to build
    private ExportRequest exportRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ExportRequestBuilder() {
        exportRequest = new ExportRequest();
    }

    public ExportRequestBuilder endDate(Long endDate) {
        exportRequest.setEndDate(endDate);
        return this;
    }

    public ExportRequestBuilder format(String format) {
        exportRequest.setFormat(format);
        return this;
    }

    public ExportRequestBuilder order(String order) {
        exportRequest.setOrder(order);
        return this;
    }

    public ExportRequestBuilder sdids(String sdids) {
        exportRequest.setSdids(sdids);
        return this;
    }

    public ExportRequestBuilder sdtids(String sdtids) {
        exportRequest.setSdtids(sdtids);
        return this;
    }

    public ExportRequestBuilder startDate(Long startDate) {
        exportRequest.setStartDate(startDate);
        return this;
    }

    public ExportRequestBuilder trialId(String trialId) {
        exportRequest.setTrialId(trialId);
        return this;
    }

    public ExportRequestBuilder uids(String uids) {
        exportRequest.setUids(uids);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExportRequest build() {
        return exportRequest;
    }
}