/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ExportRequestResponseBuilder {
    //the instance to build
    private ExportRequestResponse exportRequestResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ExportRequestResponseBuilder() {
        exportRequestResponse = new ExportRequestResponse();
    }

    /**
     * Export Request Data.
     */
    public ExportRequestResponseBuilder data(ExportRequestData data) {
        exportRequestResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExportRequestResponse build() {
        return exportRequestResponse;
    }
}