/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ExportDataArrayBuilder {
    //the instance to build
    private ExportDataArray exportDataArray;

    /**
     * Default constructor to initialize the instance
     */
    public ExportDataArrayBuilder() {
        exportDataArray = new ExportDataArray();
    }

    public ExportDataArrayBuilder exports(List<ExportData> exports) {
        exportDataArray.setExports(exports);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ExportDataArray build() {
        return exportDataArray;
    }
}