/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FieldPresenceEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4771181489403790506L;
    private String sdid;
    private String fieldPresence;
    private long startDate;
    private long endDate;
    private String interval;
    private long size;
    private List<FieldPresence> data;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fieldPresence")
    public String getFieldPresence ( ) { 
        return this.fieldPresence;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fieldPresence")
    public void setFieldPresence (String value) { 
        this.fieldPresence = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("startDate")
    public long getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("startDate")
    public void setStartDate (long value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("endDate")
    public long getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("endDate")
    public void setEndDate (long value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("interval")
    public String getInterval ( ) { 
        return this.interval;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("interval")
    public void setInterval (String value) { 
        this.interval = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("size")
    public long getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("size")
    public void setSize (long value) { 
        this.size = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public List<FieldPresence> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (List<FieldPresence> value) { 
        this.data = value;
    }
 
}
 