/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FieldPath 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5674747220487059039L;
    private List<NonEmptyString> path;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("path")
    public List<NonEmptyString> getPath ( ) { 
        return this.path;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("path")
    public void setPath (List<NonEmptyString> value) { 
        this.path = value;
    }
 
}
 