/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FieldsActions 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4798887963877908211L;
    private LinkedHashMap<String, Object> fields;
    private LinkedHashMap<String, Object> actions;
    /** GETTER
     * Message Fields
     */
    @JsonGetter("fields")
    public LinkedHashMap<String, Object> getFields ( ) { 
        return this.fields;
    }
    
    /** SETTER
     * Message Fields
     */
    @JsonSetter("fields")
    public void setFields (LinkedHashMap<String, Object> value) { 
        this.fields = value;
    }
 
    /** GETTER
     * Actions
     */
    @JsonGetter("actions")
    public LinkedHashMap<String, Object> getActions ( ) { 
        return this.actions;
    }
    
    /** SETTER
     * Actions
     */
    @JsonSetter("actions")
    public void setActions (LinkedHashMap<String, Object> value) { 
        this.actions = value;
    }
 
}
 