/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class FieldPathBuilder {
    //the instance to build
    private FieldPath fieldPath;

    /**
     * Default constructor to initialize the instance
     */
    public FieldPathBuilder() {
        fieldPath = new FieldPath();
    }

    public FieldPathBuilder path(List<NonEmptyString> path) {
        fieldPath.setPath(path);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FieldPath build() {
        return fieldPath;
    }
}