/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class FieldPresenceBuilder {
    //the instance to build
    private FieldPresence fieldPresence;

    /**
     * Default constructor to initialize the instance
     */
    public FieldPresenceBuilder() {
        fieldPresence = new FieldPresence();
    }

    public FieldPresenceBuilder startDate(long startDate) {
        fieldPresence.setStartDate(startDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FieldPresence build() {
        return fieldPresence;
    }
}