/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ManifestVersions 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5705533466725516710L;
    private List<String> versions;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("versions")
    public List<String> getVersions ( ) { 
        return this.versions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("versions")
    public void setVersions (List<String> value) { 
        this.versions = value;
    }
 
}
 