/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ManifestPropertiesEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5445382706910816272L;
    private ManifestProperties data;
    /** GETTER
     * Manifest Properties
     */
    @JsonGetter("data")
    public ManifestProperties getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Manifest Properties
     */
    @JsonSetter("data")
    public void setData (ManifestProperties value) { 
        this.data = value;
    }
 
}
 