/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ManifestVersionsBuilder {
    //the instance to build
    private ManifestVersions manifestVersions;

    /**
     * Default constructor to initialize the instance
     */
    public ManifestVersionsBuilder() {
        manifestVersions = new ManifestVersions();
    }

    public ManifestVersionsBuilder versions(List<String> versions) {
        manifestVersions.setVersions(versions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ManifestVersions build() {
        return manifestVersions;
    }
}