/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ManifestPropertiesBuilder {
    //the instance to build
    private ManifestProperties manifestProperties;

    /**
     * Default constructor to initialize the instance
     */
    public ManifestPropertiesBuilder() {
        manifestProperties = new ManifestProperties();
    }

    /**
     * Fields and Actions
     */
    public ManifestPropertiesBuilder properties(FieldsActions properties) {
        manifestProperties.setProperties(properties);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ManifestProperties build() {
        return manifestProperties;
    }
}