/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ManifestPropertiesEnvelopeBuilder {
    //the instance to build
    private ManifestPropertiesEnvelope manifestPropertiesEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public ManifestPropertiesEnvelopeBuilder() {
        manifestPropertiesEnvelope = new ManifestPropertiesEnvelope();
    }

    /**
     * Manifest Properties
     */
    public ManifestPropertiesEnvelopeBuilder data(ManifestProperties data) {
        manifestPropertiesEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ManifestPropertiesEnvelope build() {
        return manifestPropertiesEnvelope;
    }
}