/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ManifestVersionsEnvelopeBuilder {
    //the instance to build
    private ManifestVersionsEnvelope manifestVersionsEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public ManifestVersionsEnvelopeBuilder() {
        manifestVersionsEnvelope = new ManifestVersionsEnvelope();
    }

    /**
     * Manifest Versions
     */
    public ManifestVersionsEnvelopeBuilder data(ManifestVersions data) {
        manifestVersionsEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ManifestVersionsEnvelope build() {
        return manifestVersionsEnvelope;
    }
}