/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MessageIDEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4748723676804047012L;
    private MessageID data;
    /** GETTER
     * Mesage ID.
     */
    @JsonGetter("data")
    public MessageID getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Mesage ID.
     */
    @JsonSetter("data")
    public void setData (MessageID value) { 
        this.data = value;
    }
 
}
 