/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class MessageOutBuilder {
    //the instance to build
    private MessageOut messageOut;

    /**
     * Default constructor to initialize the instance
     */
    public MessageOutBuilder() {
        messageOut = new MessageOut();
    }

    /**
     * Message ID.
     */
    public MessageOutBuilder mid(String mid) {
        messageOut.setMid(mid);
        return this;
    }

    /**
     * User ID.
     */
    public MessageOutBuilder uid(String uid) {
        messageOut.setUid(uid);
        return this;
    }

    /**
     * Source Device Type ID.
     */
    public MessageOutBuilder sdtid(String sdtid) {
        messageOut.setSdtid(sdtid);
        return this;
    }

    /**
     * Created Timestamp (past, present or future). Defaults to current time if not provided.
     */
    public MessageOutBuilder cts(Long cts) {
        messageOut.setCts(cts);
        return this;
    }

    /**
     * Manifest Version.
     */
    public MessageOutBuilder mv(Integer mv) {
        messageOut.setMv(mv);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MessageOut build() {
        return messageOut;
    }
}