/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class MessageIDBuilder {
    //the instance to build
    private MessageID messageID;

    /**
     * Default constructor to initialize the instance
     */
    public MessageIDBuilder() {
        messageID = new MessageID();
    }

    /**
     * Message ID.
     */
    public MessageIDBuilder mid(String mid) {
        messageID.setMid(mid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MessageID build() {
        return messageID;
    }
}