/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MessageID 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5662351621425697440L;
    private String mid;
    /** GETTER
     * Message ID.
     */
    @JsonGetter("mid")
    public String getMid ( ) { 
        return this.mid;
    }
    
    /** SETTER
     * Message ID.
     */
    @JsonSetter("mid")
    public void setMid (String value) { 
        this.mid = value;
    }
 
}
 