/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Message 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4835554303951100913L;
    private LinkedHashMap<String, Object> data;
    private String sdid;
    private Long ts;
    private String type = "message";
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public LinkedHashMap<String, Object> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (LinkedHashMap<String, Object> value) { 
        this.data = value;
    }
 
    /** GETTER
     * Source Device ID.
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * Source Device ID.
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
    /** GETTER
     * Timestamp (past, present or future). Defaults to current time if not provided.
     */
    @JsonGetter("ts")
    public Long getTs ( ) { 
        return this.ts;
    }
    
    /** SETTER
     * Timestamp (past, present or future). Defaults to current time if not provided.
     */
    @JsonSetter("ts")
    public void setTs (Long value) { 
        this.ts = value;
    }
 
    /** GETTER
     * Type - message.
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type - message.
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 