/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MetadataQueryEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4639039209153548595L;
    private Integer total;
    private LinkedHashMap<String, Object> data;
    private Integer offset;
    private Integer count;
    /** GETTER
     * Number of results found
     */
    @JsonGetter("total")
    public Integer getTotal ( ) { 
        return this.total;
    }
    
    /** SETTER
     * Number of results found
     */
    @JsonSetter("total")
    public void setTotal (Integer value) { 
        this.total = value;
    }
 
    /** GETTER
     * Array of objects with device's metadata
     */
    @JsonGetter("data")
    public LinkedHashMap<String, Object> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Array of objects with device's metadata
     */
    @JsonSetter("data")
    public void setData (LinkedHashMap<String, Object> value) { 
        this.data = value;
    }
 
    /** GETTER
     * Page starting position
     */
    @JsonGetter("offset")
    public Integer getOffset ( ) { 
        return this.offset;
    }
    
    /** SETTER
     * Page starting position
     */
    @JsonSetter("offset")
    public void setOffset (Integer value) { 
        this.offset = value;
    }
 
    /** GETTER
     * Page size
     */
    @JsonGetter("count")
    public Integer getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * Page size
     */
    @JsonSetter("count")
    public void setCount (Integer value) { 
        this.count = value;
    }
 
}
 