/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class MetadataQueryEnvelopeBuilder {
    //the instance to build
    private MetadataQueryEnvelope metadataQueryEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public MetadataQueryEnvelopeBuilder() {
        metadataQueryEnvelope = new MetadataQueryEnvelope();
    }

    /**
     * Number of results found
     */
    public MetadataQueryEnvelopeBuilder total(Integer total) {
        metadataQueryEnvelope.setTotal(total);
        return this;
    }

    /**
     * Array of objects with device's metadata
     */
    public MetadataQueryEnvelopeBuilder data(LinkedHashMap<String, Object> data) {
        metadataQueryEnvelope.setData(data);
        return this;
    }

    /**
     * Page starting position
     */
    public MetadataQueryEnvelopeBuilder offset(Integer offset) {
        metadataQueryEnvelope.setOffset(offset);
        return this;
    }

    /**
     * Page size
     */
    public MetadataQueryEnvelopeBuilder count(Integer count) {
        metadataQueryEnvelope.setCount(count);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MetadataQueryEnvelope build() {
        return metadataQueryEnvelope;
    }
}