/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MetadataEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4856751033894944756L;
    private LinkedHashMap<String, Object> data;
    /** GETTER
     * Free form JSON object
     */
    @JsonGetter("data")
    public LinkedHashMap<String, Object> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Free form JSON object
     */
    @JsonSetter("data")
    public void setData (LinkedHashMap<String, Object> value) { 
        this.data = value;
    }
 
}
 