/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class MetadataPropertiesEnvelopeBuilder {
    //the instance to build
    private MetadataPropertiesEnvelope metadataPropertiesEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public MetadataPropertiesEnvelopeBuilder() {
        metadataPropertiesEnvelope = new MetadataPropertiesEnvelope();
    }

    public MetadataPropertiesEnvelopeBuilder data(LinkedHashMap<String, Object> data) {
        metadataPropertiesEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MetadataPropertiesEnvelope build() {
        return metadataPropertiesEnvelope;
    }
}