/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class NormalizedActionsEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5696571589127622789L;
    private long count;
    private long size;
    private List<NormalizedAction> data;
    private String ddids;
    private String ddid;
    private String uid;
    private Long startDate;
    private Long endDate;
    private String order;
    private String next;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("count")
    public long getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("count")
    public void setCount (long value) { 
        this.count = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("size")
    public long getSize ( ) { 
        return this.size;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("size")
    public void setSize (long value) { 
        this.size = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public List<NormalizedAction> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (List<NormalizedAction> value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ddids")
    public String getDdids ( ) { 
        return this.ddids;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ddids")
    public void setDdids (String value) { 
        this.ddids = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ddid")
    public String getDdid ( ) { 
        return this.ddid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ddid")
    public void setDdid (String value) { 
        this.ddid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("startDate")
    public Long getStartDate ( ) { 
        return this.startDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("startDate")
    public void setStartDate (Long value) { 
        this.startDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("endDate")
    public Long getEndDate ( ) { 
        return this.endDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("endDate")
    public void setEndDate (Long value) { 
        this.endDate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("order")
    public String getOrder ( ) { 
        return this.order;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("order")
    public void setOrder (String value) { 
        this.order = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("next")
    public String getNext ( ) { 
        return this.next;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("next")
    public void setNext (String value) { 
        this.next = value;
    }
 
}
 