/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class NormalizedActionsEnvelopeBuilder {
    //the instance to build
    private NormalizedActionsEnvelope normalizedActionsEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public NormalizedActionsEnvelopeBuilder() {
        normalizedActionsEnvelope = new NormalizedActionsEnvelope();
    }

    public NormalizedActionsEnvelopeBuilder count(long count) {
        normalizedActionsEnvelope.setCount(count);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder size(long size) {
        normalizedActionsEnvelope.setSize(size);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder data(List<NormalizedAction> data) {
        normalizedActionsEnvelope.setData(data);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder ddids(String ddids) {
        normalizedActionsEnvelope.setDdids(ddids);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder ddid(String ddid) {
        normalizedActionsEnvelope.setDdid(ddid);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder uid(String uid) {
        normalizedActionsEnvelope.setUid(uid);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder startDate(Long startDate) {
        normalizedActionsEnvelope.setStartDate(startDate);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder endDate(Long endDate) {
        normalizedActionsEnvelope.setEndDate(endDate);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder order(String order) {
        normalizedActionsEnvelope.setOrder(order);
        return this;
    }

    public NormalizedActionsEnvelopeBuilder next(String next) {
        normalizedActionsEnvelope.setNext(next);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NormalizedActionsEnvelope build() {
        return normalizedActionsEnvelope;
    }
}