/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class NormalizedMessagesEnvelopeBuilder {
    //the instance to build
    private NormalizedMessagesEnvelope normalizedMessagesEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public NormalizedMessagesEnvelopeBuilder() {
        normalizedMessagesEnvelope = new NormalizedMessagesEnvelope();
    }

    public NormalizedMessagesEnvelopeBuilder count(long count) {
        normalizedMessagesEnvelope.setCount(count);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder size(long size) {
        normalizedMessagesEnvelope.setSize(size);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder data(List<NormalizedMessage> data) {
        normalizedMessagesEnvelope.setData(data);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder sdids(String sdids) {
        normalizedMessagesEnvelope.setSdids(sdids);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder sdid(String sdid) {
        normalizedMessagesEnvelope.setSdid(sdid);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder uid(String uid) {
        normalizedMessagesEnvelope.setUid(uid);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder startDate(Long startDate) {
        normalizedMessagesEnvelope.setStartDate(startDate);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder endDate(Long endDate) {
        normalizedMessagesEnvelope.setEndDate(endDate);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder order(String order) {
        normalizedMessagesEnvelope.setOrder(order);
        return this;
    }

    public NormalizedMessagesEnvelopeBuilder next(String next) {
        normalizedMessagesEnvelope.setNext(next);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NormalizedMessagesEnvelope build() {
        return normalizedMessagesEnvelope;
    }
}