/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class NormalizedActionBuilder {
    //the instance to build
    private NormalizedAction normalizedAction;

    /**
     * Default constructor to initialize the instance
     */
    public NormalizedActionBuilder() {
        normalizedAction = new NormalizedAction();
    }

    public NormalizedActionBuilder cts(long cts) {
        normalizedAction.setCts(cts);
        return this;
    }

    public NormalizedActionBuilder ts(long ts) {
        normalizedAction.setTs(ts);
        return this;
    }

    public NormalizedActionBuilder mid(String mid) {
        normalizedAction.setMid(mid);
        return this;
    }

    public NormalizedActionBuilder ddid(String ddid) {
        normalizedAction.setDdid(ddid);
        return this;
    }

    public NormalizedActionBuilder ddtid(String ddtid) {
        normalizedAction.setDdtid(ddtid);
        return this;
    }

    public NormalizedActionBuilder uid(String uid) {
        normalizedAction.setUid(uid);
        return this;
    }

    public NormalizedActionBuilder mv(int mv) {
        normalizedAction.setMv(mv);
        return this;
    }

    /**
     * Holds an array of Actions
     */
    public NormalizedActionBuilder data(ActionArray data) {
        normalizedAction.setData(data);
        return this;
    }

    public NormalizedActionBuilder sdid(String sdid) {
        normalizedAction.setSdid(sdid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NormalizedAction build() {
        return normalizedAction;
    }
}