/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class NotifMessageArrayBuilder {
    //the instance to build
    private NotifMessageArray notifMessageArray;

    /**
     * Default constructor to initialize the instance
     */
    public NotifMessageArrayBuilder() {
        notifMessageArray = new NotifMessageArray();
    }

    public NotifMessageArrayBuilder messages(List<NotifMessage> messages) {
        notifMessageArray.setMessages(messages);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NotifMessageArray build() {
        return notifMessageArray;
    }
}