/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class NotifMessageBuilder {
    //the instance to build
    private NotifMessage notifMessage;

    /**
     * Default constructor to initialize the instance
     */
    public NotifMessageBuilder() {
        notifMessage = new NotifMessage();
    }

    public NotifMessageBuilder uid(String uid) {
        notifMessage.setUid(uid);
        return this;
    }

    public NotifMessageBuilder cts(Long cts) {
        notifMessage.setCts(cts);
        return this;
    }

    public NotifMessageBuilder data(LinkedHashMap<String, Object> data) {
        notifMessage.setData(data);
        return this;
    }

    public NotifMessageBuilder mid(String mid) {
        notifMessage.setMid(mid);
        return this;
    }

    public NotifMessageBuilder sdid(String sdid) {
        notifMessage.setSdid(sdid);
        return this;
    }

    public NotifMessageBuilder mv(String mv) {
        notifMessage.setMv(mv);
        return this;
    }

    public NotifMessageBuilder sdtid(String sdtid) {
        notifMessage.setSdtid(sdtid);
        return this;
    }

    public NotifMessageBuilder ts(Long ts) {
        notifMessage.setTs(ts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NotifMessage build() {
        return notifMessage;
    }
}