/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class NotifMessagesResponseBuilder {
    //the instance to build
    private NotifMessagesResponse notifMessagesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public NotifMessagesResponseBuilder() {
        notifMessagesResponse = new NotifMessagesResponse();
    }

    public NotifMessagesResponseBuilder total(Long total) {
        notifMessagesResponse.setTotal(total);
        return this;
    }

    public NotifMessagesResponseBuilder offset(Integer offset) {
        notifMessagesResponse.setOffset(offset);
        return this;
    }

    public NotifMessagesResponseBuilder data(NotifMessageArray data) {
        notifMessagesResponse.setData(data);
        return this;
    }

    public NotifMessagesResponseBuilder count(Integer count) {
        notifMessagesResponse.setCount(count);
        return this;
    }

    public NotifMessagesResponseBuilder order(String order) {
        notifMessagesResponse.setOrder(order);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public NotifMessagesResponse build() {
        return notifMessagesResponse;
    }
}