/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class NotifMessage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5407821649865920364L;
    private String uid;
    private Long cts;
    private LinkedHashMap<String, Object> data;
    private String mid;
    private String sdid;
    private String mv;
    private String sdtid;
    private Long ts;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cts")
    public Long getCts ( ) { 
        return this.cts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cts")
    public void setCts (Long value) { 
        this.cts = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public LinkedHashMap<String, Object> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (LinkedHashMap<String, Object> value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mid")
    public String getMid ( ) { 
        return this.mid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mid")
    public void setMid (String value) { 
        this.mid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mv")
    public String getMv ( ) { 
        return this.mv;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mv")
    public void setMv (String value) { 
        this.mv = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdtid")
    public String getSdtid ( ) { 
        return this.sdtid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdtid")
    public void setSdtid (String value) { 
        this.sdtid = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ts")
    public Long getTs ( ) { 
        return this.ts;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ts")
    public void setTs (Long value) { 
        this.ts = value;
    }
 
}
 