/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum OwnerEnum {
    ALL, //TODO: Write general description for this element
    SHARED_WITH_ME, //TODO: Write general description for this element
    ME; //TODO: Write general description for this element

    private static TreeMap<String, OwnerEnum> valueMap = new TreeMap<String, OwnerEnum>();
    private String value;

    static {
        ALL.value = "ALL";
        SHARED_WITH_ME.value = "SHARED_WITH_ME";
        ME.value = "ME";

        valueMap.put("ALL", ALL);
        valueMap.put("SHARED_WITH_ME", SHARED_WITH_ME);
        valueMap.put("ME", ME);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static OwnerEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of OwnerEnum values to list of string values
     * @param toConvert The list of OwnerEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<OwnerEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (OwnerEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 