/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class PresenceEnvelopeBuilder {
    //the instance to build
    private PresenceEnvelope presenceEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public PresenceEnvelopeBuilder() {
        presenceEnvelope = new PresenceEnvelope();
    }

    public PresenceEnvelopeBuilder data(PresenceModel data) {
        presenceEnvelope.setData(data);
        return this;
    }

    public PresenceEnvelopeBuilder sdid(String sdid) {
        presenceEnvelope.setSdid(sdid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PresenceEnvelope build() {
        return presenceEnvelope;
    }
}