/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PresenceModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5685200801859734292L;
    private Boolean connected;
    private Long lastSeenOn;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("connected")
    public Boolean getConnected ( ) { 
        return this.connected;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("connected")
    public void setConnected (Boolean value) { 
        this.connected = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastSeenOn")
    public Long getLastSeenOn ( ) { 
        return this.lastSeenOn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastSeenOn")
    public void setLastSeenOn (Long value) { 
        this.lastSeenOn = value;
    }
 
}
 