/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class PropertiesEnvelopeBuilder {
    //the instance to build
    private PropertiesEnvelope propertiesEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public PropertiesEnvelopeBuilder() {
        propertiesEnvelope = new PropertiesEnvelope();
    }

    /**
     * User Application Properties
     */
    public PropertiesEnvelopeBuilder data(AppProperties data) {
        propertiesEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PropertiesEnvelope build() {
        return propertiesEnvelope;
    }
}