/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class RefreshTokenResponseBuilder {
    //the instance to build
    private RefreshTokenResponse refreshTokenResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RefreshTokenResponseBuilder() {
        refreshTokenResponse = new RefreshTokenResponse();
    }

    public RefreshTokenResponseBuilder accessToken(String accessToken) {
        refreshTokenResponse.setAccessToken(accessToken);
        return this;
    }

    public RefreshTokenResponseBuilder expiresIn(Long expiresIn) {
        refreshTokenResponse.setExpiresIn(expiresIn);
        return this;
    }

    public RefreshTokenResponseBuilder refreshToken(String refreshToken) {
        refreshTokenResponse.setRefreshToken(refreshToken);
        return this;
    }

    public RefreshTokenResponseBuilder tokenType(String tokenType) {
        refreshTokenResponse.setTokenType(tokenType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RefreshTokenResponse build() {
        return refreshTokenResponse;
    }
}