/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RegisterMessage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5372813360447502879L;
    private String cid;
    private String authorization;
    private String sdid;
    private Long ts;
    private String type = "register";
    /** GETTER
     * Confirmation ID.
     */
    @JsonGetter("cid")
    public String getCid ( ) { 
        return this.cid;
    }
    
    /** SETTER
     * Confirmation ID.
     */
    @JsonSetter("cid")
    public void setCid (String value) { 
        this.cid = value;
    }
 
    /** GETTER
     * Authorization header containing access token (Bearer <access_token>).
     */
    @JsonGetter("authorization")
    public String getAuthorization ( ) { 
        return this.authorization;
    }
    
    /** SETTER
     * Authorization header containing access token (Bearer <access_token>).
     */
    @JsonSetter("authorization")
    public void setAuthorization (String value) { 
        this.authorization = value;
    }
 
    /** GETTER
     * Source Device ID.
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * Source Device ID.
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
    /** GETTER
     * Timestamp (past, present or future). Defaults to current time if not provided.
     */
    @JsonGetter("ts")
    public Long getTs ( ) { 
        return this.ts;
    }
    
    /** SETTER
     * Timestamp (past, present or future). Defaults to current time if not provided.
     */
    @JsonSetter("ts")
    public void setTs (Long value) { 
        this.ts = value;
    }
 
    /** GETTER
     * Type.
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Type.
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 