/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class RuleErrorBuilder {
    //the instance to build
    private RuleError ruleError;

    /**
     * Default constructor to initialize the instance
     */
    public RuleErrorBuilder() {
        ruleError = new RuleError();
    }

    public RuleErrorBuilder errorCode(Integer errorCode) {
        ruleError.setErrorCode(errorCode);
        return this;
    }

    public RuleErrorBuilder fieldPath(FieldPath fieldPath) {
        ruleError.setFieldPath(fieldPath);
        return this;
    }

    public RuleErrorBuilder messageArgs(List<String> messageArgs) {
        ruleError.setMessageArgs(messageArgs);
        return this;
    }

    public RuleErrorBuilder messageKey(String messageKey) {
        ruleError.setMessageKey(messageKey);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RuleError build() {
        return ruleError;
    }
}