/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RuleError 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5336840279411662264L;
    private Integer errorCode;
    private FieldPath fieldPath;
    private List<String> messageArgs;
    private String messageKey;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("errorCode")
    public Integer getErrorCode ( ) { 
        return this.errorCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("errorCode")
    public void setErrorCode (Integer value) { 
        this.errorCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fieldPath")
    public FieldPath getFieldPath ( ) { 
        return this.fieldPath;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fieldPath")
    public void setFieldPath (FieldPath value) { 
        this.fieldPath = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("messageArgs")
    public List<String> getMessageArgs ( ) { 
        return this.messageArgs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("messageArgs")
    public void setMessageArgs (List<String> value) { 
        this.messageArgs = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("messageKey")
    public String getMessageKey ( ) { 
        return this.messageKey;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("messageKey")
    public void setMessageKey (String value) { 
        this.messageKey = value;
    }
 
}
 