/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class RuleUpdateInfoBuilder {
    //the instance to build
    private RuleUpdateInfo ruleUpdateInfo;

    /**
     * Default constructor to initialize the instance
     */
    public RuleUpdateInfoBuilder() {
        ruleUpdateInfo = new RuleUpdateInfo();
    }

    /**
     * Description
     */
    public RuleUpdateInfoBuilder description(String description) {
        ruleUpdateInfo.setDescription(description);
        return this;
    }

    /**
     * Is Enabled
     */
    public RuleUpdateInfoBuilder enabled(Boolean enabled) {
        ruleUpdateInfo.setEnabled(enabled);
        return this;
    }

    /**
     * Name
     */
    public RuleUpdateInfoBuilder name(String name) {
        ruleUpdateInfo.setName(name);
        return this;
    }

    /**
     * Rule
     */
    public RuleUpdateInfoBuilder rule(LinkedHashMap<String, Object> rule) {
        ruleUpdateInfo.setRule(rule);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RuleUpdateInfo build() {
        return ruleUpdateInfo;
    }
}