/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class RuleCreationInfoBuilder {
    //the instance to build
    private RuleCreationInfo ruleCreationInfo;

    /**
     * Default constructor to initialize the instance
     */
    public RuleCreationInfoBuilder() {
        ruleCreationInfo = new RuleCreationInfo();
    }

    /**
     * Description
     */
    public RuleCreationInfoBuilder description(String description) {
        ruleCreationInfo.setDescription(description);
        return this;
    }

    /**
     * Is Enabled
     */
    public RuleCreationInfoBuilder enabled(Boolean enabled) {
        ruleCreationInfo.setEnabled(enabled);
        return this;
    }

    /**
     * Name
     */
    public RuleCreationInfoBuilder name(String name) {
        ruleCreationInfo.setName(name);
        return this;
    }

    /**
     * Rule
     */
    public RuleCreationInfoBuilder rule(LinkedHashMap<String, Object> rule) {
        ruleCreationInfo.setRule(rule);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RuleCreationInfo build() {
        return ruleCreationInfo;
    }
}