/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class RuleArrayBuilder {
    //the instance to build
    private RuleArray ruleArray;

    /**
     * Default constructor to initialize the instance
     */
    public RuleArrayBuilder() {
        ruleArray = new RuleArray();
    }

    public RuleArrayBuilder rules(List<OutputRule> rules) {
        ruleArray.setRules(rules);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RuleArray build() {
        return ruleArray;
    }
}