/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class SnapshotsResponseEnvelopeBuilder {
    //the instance to build
    private SnapshotsResponseEnvelope snapshotsResponseEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public SnapshotsResponseEnvelopeBuilder() {
        snapshotsResponseEnvelope = new SnapshotsResponseEnvelope();
    }

    public SnapshotsResponseEnvelopeBuilder data(SnapshotResponses data) {
        snapshotsResponseEnvelope.setData(data);
        return this;
    }

    public SnapshotsResponseEnvelopeBuilder sdid(String sdid) {
        snapshotsResponseEnvelope.setSdid(sdid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SnapshotsResponseEnvelope build() {
        return snapshotsResponseEnvelope;
    }
}