/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class SnapshotResponseBuilder {
    //the instance to build
    private SnapshotResponse snapshotResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SnapshotResponseBuilder() {
        snapshotResponse = new SnapshotResponse();
    }

    public SnapshotResponseBuilder data(LinkedHashMap<String, Object> data) {
        snapshotResponse.setData(data);
        return this;
    }

    public SnapshotResponseBuilder sdid(String sdid) {
        snapshotResponse.setSdid(sdid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SnapshotResponse build() {
        return snapshotResponse;
    }
}