/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SnapshotsResponseEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4965273647022529612L;
    private SnapshotResponses data;
    private String sdid;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("data")
    public SnapshotResponses getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("data")
    public void setData (SnapshotResponses value) { 
        this.data = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
}
 