/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SubscriptionArray 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4789832138813843203L;
    private List<Subscription> subscriptions;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("subscriptions")
    public List<Subscription> getSubscriptions ( ) { 
        return this.subscriptions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("subscriptions")
    public void setSubscriptions (List<Subscription> value) { 
        this.subscriptions = value;
    }
 
}
 