/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Subscription 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5717923557508934179L;
    private String awsRegion;
    private Boolean includeSharedDevices;
    private String description;
    private String awsKey;
    private String awsSecret;
    private Long createdOn;
    private String awsKinesisStreamName;
    private String uid;
    private String messageType;
    private String ddid;
    private String subscriptionType;
    private String name;
    private String sdid;
    private String callbackUrl;
    private String id;
    private String aid;
    private String sdtid;
    /** GETTER
     * AWS region (if subscriptionType is awsKinesis
     */
    @JsonGetter("awsRegion")
    public String getAwsRegion ( ) { 
        return this.awsRegion;
    }
    
    /** SETTER
     * AWS region (if subscriptionType is awsKinesis
     */
    @JsonSetter("awsRegion")
    public void setAwsRegion (String value) { 
        this.awsRegion = value;
    }
 
    /** GETTER
     * Include Shared Devices
     */
    @JsonGetter("includeSharedDevices")
    public Boolean getIncludeSharedDevices ( ) { 
        return this.includeSharedDevices;
    }
    
    /** SETTER
     * Include Shared Devices
     */
    @JsonSetter("includeSharedDevices")
    public void setIncludeSharedDevices (Boolean value) { 
        this.includeSharedDevices = value;
    }
 
    /** GETTER
     * Description
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * Description
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * AWS key (if subscriptionType is awsKinesis
     */
    @JsonGetter("awsKey")
    public String getAwsKey ( ) { 
        return this.awsKey;
    }
    
    /** SETTER
     * AWS key (if subscriptionType is awsKinesis
     */
    @JsonSetter("awsKey")
    public void setAwsKey (String value) { 
        this.awsKey = value;
    }
 
    /** GETTER
     * AWS secret (if subscriptionType is awsKinesis
     */
    @JsonGetter("awsSecret")
    public String getAwsSecret ( ) { 
        return this.awsSecret;
    }
    
    /** SETTER
     * AWS secret (if subscriptionType is awsKinesis
     */
    @JsonSetter("awsSecret")
    public void setAwsSecret (String value) { 
        this.awsSecret = value;
    }
 
    /** GETTER
     * Creation timestamp
     */
    @JsonGetter("createdOn")
    public Long getCreatedOn ( ) { 
        return this.createdOn;
    }
    
    /** SETTER
     * Creation timestamp
     */
    @JsonSetter("createdOn")
    public void setCreatedOn (Long value) { 
        this.createdOn = value;
    }
 
    /** GETTER
     * AWS Kinesis stream name (if subscriptionType is awsKinesis
     */
    @JsonGetter("awsKinesisStreamName")
    public String getAwsKinesisStreamName ( ) { 
        return this.awsKinesisStreamName;
    }
    
    /** SETTER
     * AWS Kinesis stream name (if subscriptionType is awsKinesis
     */
    @JsonSetter("awsKinesisStreamName")
    public void setAwsKinesisStreamName (String value) { 
        this.awsKinesisStreamName = value;
    }
 
    /** GETTER
     * User ID
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * User ID
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
    /** GETTER
     * Message type
     */
    @JsonGetter("messageType")
    public String getMessageType ( ) { 
        return this.messageType;
    }
    
    /** SETTER
     * Message type
     */
    @JsonSetter("messageType")
    public void setMessageType (String value) { 
        this.messageType = value;
    }
 
    /** GETTER
     * Destination device ID
     */
    @JsonGetter("ddid")
    public String getDdid ( ) { 
        return this.ddid;
    }
    
    /** SETTER
     * Destination device ID
     */
    @JsonSetter("ddid")
    public void setDdid (String value) { 
        this.ddid = value;
    }
 
    /** GETTER
     * Subscription type (either httpCallback or awsKinesis, default to httpCallback)
     */
    @JsonGetter("subscriptionType")
    public String getSubscriptionType ( ) { 
        return this.subscriptionType;
    }
    
    /** SETTER
     * Subscription type (either httpCallback or awsKinesis, default to httpCallback)
     */
    @JsonSetter("subscriptionType")
    public void setSubscriptionType (String value) { 
        this.subscriptionType = value;
    }
 
    /** GETTER
     * Name
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Source device ID
     */
    @JsonGetter("sdid")
    public String getSdid ( ) { 
        return this.sdid;
    }
    
    /** SETTER
     * Source device ID
     */
    @JsonSetter("sdid")
    public void setSdid (String value) { 
        this.sdid = value;
    }
 
    /** GETTER
     * Callback URL
     */
    @JsonGetter("callbackUrl")
    public String getCallbackUrl ( ) { 
        return this.callbackUrl;
    }
    
    /** SETTER
     * Callback URL
     */
    @JsonSetter("callbackUrl")
    public void setCallbackUrl (String value) { 
        this.callbackUrl = value;
    }
 
    /** GETTER
     * Subscription ID
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Subscription ID
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * Application ID
     */
    @JsonGetter("aid")
    public String getAid ( ) { 
        return this.aid;
    }
    
    /** SETTER
     * Application ID
     */
    @JsonSetter("aid")
    public void setAid (String value) { 
        this.aid = value;
    }
 
    /** GETTER
     * Source device type ID
     */
    @JsonGetter("sdtid")
    public String getSdtid ( ) { 
        return this.sdtid;
    }
    
    /** SETTER
     * Source device type ID
     */
    @JsonSetter("sdtid")
    public void setSdtid (String value) { 
        this.sdtid = value;
    }
 
}
 