/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class SubscriptionArrayBuilder {
    //the instance to build
    private SubscriptionArray subscriptionArray;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionArrayBuilder() {
        subscriptionArray = new SubscriptionArray();
    }

    public SubscriptionArrayBuilder subscriptions(List<Subscription> subscriptions) {
        subscriptionArray.setSubscriptions(subscriptions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionArray build() {
        return subscriptionArray;
    }
}