/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class SubscriptionInfoBuilder {
    //the instance to build
    private SubscriptionInfo subscriptionInfo;

    /**
     * Default constructor to initialize the instance
     */
    public SubscriptionInfoBuilder() {
        subscriptionInfo = new SubscriptionInfo();
    }

    /**
     * AWS region (if subscriptionType is awsKinesis
     */
    public SubscriptionInfoBuilder awsRegion(String awsRegion) {
        subscriptionInfo.setAwsRegion(awsRegion);
        return this;
    }

    /**
     * Description
     */
    public SubscriptionInfoBuilder description(String description) {
        subscriptionInfo.setDescription(description);
        return this;
    }

    /**
     * AWS key (if subscriptionType is awsKinesis
     */
    public SubscriptionInfoBuilder awsKey(String awsKey) {
        subscriptionInfo.setAwsKey(awsKey);
        return this;
    }

    /**
     * AWS secret (if subscriptionType is awsKinesis
     */
    public SubscriptionInfoBuilder awsSecret(String awsSecret) {
        subscriptionInfo.setAwsSecret(awsSecret);
        return this;
    }

    /**
     * AWS Kinesis stream name (if subscriptionType is awsKinesis
     */
    public SubscriptionInfoBuilder awsKinesisStreamName(String awsKinesisStreamName) {
        subscriptionInfo.setAwsKinesisStreamName(awsKinesisStreamName);
        return this;
    }

    /**
     * User ID
     */
    public SubscriptionInfoBuilder uid(String uid) {
        subscriptionInfo.setUid(uid);
        return this;
    }

    /**
     * Message type
     */
    public SubscriptionInfoBuilder messageType(String messageType) {
        subscriptionInfo.setMessageType(messageType);
        return this;
    }

    /**
     * Destination device ID
     */
    public SubscriptionInfoBuilder ddid(String ddid) {
        subscriptionInfo.setDdid(ddid);
        return this;
    }

    /**
     * Subscription type (either httpCallback or awsKinesis, default to httpCallback)
     */
    public SubscriptionInfoBuilder subscriptionType(String subscriptionType) {
        subscriptionInfo.setSubscriptionType(subscriptionType);
        return this;
    }

    /**
     * Name
     */
    public SubscriptionInfoBuilder name(String name) {
        subscriptionInfo.setName(name);
        return this;
    }

    /**
     * Source device ID
     */
    public SubscriptionInfoBuilder sdid(String sdid) {
        subscriptionInfo.setSdid(sdid);
        return this;
    }

    /**
     * Callback URL
     */
    public SubscriptionInfoBuilder callbackUrl(String callbackUrl) {
        subscriptionInfo.setCallbackUrl(callbackUrl);
        return this;
    }

    /**
     * Source device type ID
     */
    public SubscriptionInfoBuilder sdtid(String sdtid) {
        subscriptionInfo.setSdtid(sdtid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubscriptionInfo build() {
        return subscriptionInfo;
    }
}