/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Tag 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5123438471085857908L;
    private String name;
    private Boolean isCategory;
    /** GETTER
     * Tag Name.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Tag Name.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Is Category.
     */
    @JsonGetter("isCategory")
    public Boolean getIsCategory ( ) { 
        return this.isCategory;
    }
    
    /** SETTER
     * Is Category.
     */
    @JsonSetter("isCategory")
    public void setIsCategory (Boolean value) { 
        this.isCategory = value;
    }
 
}
 