/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TagsEnvelopeBuilder {
    //the instance to build
    private TagsEnvelope tagsEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public TagsEnvelopeBuilder() {
        tagsEnvelope = new TagsEnvelope();
    }

    /**
     * Contains the arry of Tags.
     */
    public TagsEnvelopeBuilder data(TagArray data) {
        tagsEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TagsEnvelope build() {
        return tagsEnvelope;
    }
}