/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskByDidListEnvelopeBuilder {
    //the instance to build
    private TaskByDidListEnvelope taskByDidListEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public TaskByDidListEnvelopeBuilder() {
        taskByDidListEnvelope = new TaskByDidListEnvelope();
    }

    /**
     * Total number of tasks in list
     */
    public TaskByDidListEnvelopeBuilder total(Integer total) {
        taskByDidListEnvelope.setTotal(total);
        return this;
    }

    /**
     * Device task list envelope
     */
    public TaskByDidListEnvelopeBuilder data(TaskByDidList data) {
        taskByDidListEnvelope.setData(data);
        return this;
    }

    /**
     * Offset if using pagination
     */
    public TaskByDidListEnvelopeBuilder offset(Integer offset) {
        taskByDidListEnvelope.setOffset(offset);
        return this;
    }

    /**
     * Count for current result set
     */
    public TaskByDidListEnvelopeBuilder count(Integer count) {
        taskByDidListEnvelope.setCount(count);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskByDidListEnvelope build() {
        return taskByDidListEnvelope;
    }
}