/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskByDidListEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5149519482224212447L;
    private Integer total;
    private TaskByDidList data;
    private Integer offset;
    private Integer count;
    /** GETTER
     * Total number of tasks in list
     */
    @JsonGetter("total")
    public Integer getTotal ( ) { 
        return this.total;
    }
    
    /** SETTER
     * Total number of tasks in list
     */
    @JsonSetter("total")
    public void setTotal (Integer value) { 
        this.total = value;
    }
 
    /** GETTER
     * Device task list envelope
     */
    @JsonGetter("data")
    public TaskByDidList getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Device task list envelope
     */
    @JsonSetter("data")
    public void setData (TaskByDidList value) { 
        this.data = value;
    }
 
    /** GETTER
     * Offset if using pagination
     */
    @JsonGetter("offset")
    public Integer getOffset ( ) { 
        return this.offset;
    }
    
    /** SETTER
     * Offset if using pagination
     */
    @JsonSetter("offset")
    public void setOffset (Integer value) { 
        this.offset = value;
    }
 
    /** GETTER
     * Count for current result set
     */
    @JsonGetter("count")
    public Integer getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * Count for current result set
     */
    @JsonSetter("count")
    public void setCount (Integer value) { 
        this.count = value;
    }
 
}
 