/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskBuilder {
    //the instance to build
    private Task task;

    /**
     * Default constructor to initialize the instance
     */
    public TaskBuilder() {
        task = new Task();
    }

    /**
     * Filter
     */
    public TaskBuilder filter(String filter) {
        task.setFilter(filter);
        return this;
    }

    /**
     * Task type
     */
    public TaskBuilder taskType(String taskType) {
        task.setTaskType(taskType);
        return this;
    }

    /**
     * Modified on
     */
    public TaskBuilder modifiedOn(Long modifiedOn) {
        task.setModifiedOn(modifiedOn);
        return this;
    }

    /**
     * Device Type ID
     */
    public TaskBuilder dtid(String dtid) {
        task.setDtid(dtid);
        return this;
    }

    /**
     * Status counts
     */
    public TaskBuilder statusCounts(TaskStatusCounts statusCounts) {
        task.setStatusCounts(statusCounts);
        return this;
    }

    /**
     * Property
     */
    public TaskBuilder property(String property) {
        task.setProperty(property);
        return this;
    }

    /**
     * Task ID
     */
    public TaskBuilder id(String id) {
        task.setId(id);
        return this;
    }

    /**
     * Device IDs
     */
    public TaskBuilder dids(List<String> dids) {
        task.setDids(dids);
        return this;
    }

    /**
     * Task parameters
     */
    public TaskBuilder taskParameters(TaskParameters taskParameters) {
        task.setTaskParameters(taskParameters);
        return this;
    }

    /**
     * Created on
     */
    public TaskBuilder createdOn(Long createdOn) {
        task.setCreatedOn(createdOn);
        return this;
    }

    /**
     * Status
     */
    public TaskBuilder status(String status) {
        task.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Task build() {
        return task;
    }
}