/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskEnvelopeBuilder {
    //the instance to build
    private TaskEnvelope taskEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public TaskEnvelopeBuilder() {
        taskEnvelope = new TaskEnvelope();
    }

    /**
     * Task details envelope
     */
    public TaskEnvelopeBuilder data(Task data) {
        taskEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskEnvelope build() {
        return taskEnvelope;
    }
}