/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskRequestBuilder {
    //the instance to build
    private TaskRequest taskRequest;

    /**
     * Default constructor to initialize the instance
     */
    public TaskRequestBuilder() {
        taskRequest = new TaskRequest();
    }

    /**
     * Filter
     */
    public TaskRequestBuilder filter(String filter) {
        taskRequest.setFilter(filter);
        return this;
    }

    /**
     * Task type
     */
    public TaskRequestBuilder taskType(String taskType) {
        taskRequest.setTaskType(taskType);
        return this;
    }

    /**
     * Device Type ID
     */
    public TaskRequestBuilder dtid(String dtid) {
        taskRequest.setDtid(dtid);
        return this;
    }

    /**
     * Property
     */
    public TaskRequestBuilder property(String property) {
        taskRequest.setProperty(property);
        return this;
    }

    /**
     * Device IDs
     */
    public TaskRequestBuilder dids(List<String> dids) {
        taskRequest.setDids(dids);
        return this;
    }

    /**
     * Task parameters
     */
    public TaskRequestBuilder taskParameters(TaskParameters taskParameters) {
        taskRequest.setTaskParameters(taskParameters);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskRequest build() {
        return taskRequest;
    }
}