/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskStatusesHistoryEnvelopeBuilder {
    //the instance to build
    private TaskStatusesHistoryEnvelope taskStatusesHistoryEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public TaskStatusesHistoryEnvelopeBuilder() {
        taskStatusesHistoryEnvelope = new TaskStatusesHistoryEnvelope();
    }

    /**
     * Task statuses history
     */
    public TaskStatusesHistoryEnvelopeBuilder data(TaskHistoryList data) {
        taskStatusesHistoryEnvelope.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskStatusesHistoryEnvelope build() {
        return taskStatusesHistoryEnvelope;
    }
}