/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskListEnvelopeBuilder {
    //the instance to build
    private TaskListEnvelope taskListEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public TaskListEnvelopeBuilder() {
        taskListEnvelope = new TaskListEnvelope();
    }

    /**
     * Total
     */
    public TaskListEnvelopeBuilder total(Integer total) {
        taskListEnvelope.setTotal(total);
        return this;
    }

    /**
     * Envelope for task list
     */
    public TaskListEnvelopeBuilder data(TaskList data) {
        taskListEnvelope.setData(data);
        return this;
    }

    /**
     * Status counts
     */
    public TaskListEnvelopeBuilder statusCounts(TasksStatusCounts statusCounts) {
        taskListEnvelope.setStatusCounts(statusCounts);
        return this;
    }

    /**
     * Offset
     */
    public TaskListEnvelopeBuilder offset(Integer offset) {
        taskListEnvelope.setOffset(offset);
        return this;
    }

    /**
     * Count
     */
    public TaskListEnvelopeBuilder count(Integer count) {
        taskListEnvelope.setCount(count);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskListEnvelope build() {
        return taskListEnvelope;
    }
}