/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskStatusesEnvelopeBuilder {
    //the instance to build
    private TaskStatusesEnvelope taskStatusesEnvelope;

    /**
     * Default constructor to initialize the instance
     */
    public TaskStatusesEnvelopeBuilder() {
        taskStatusesEnvelope = new TaskStatusesEnvelope();
    }

    /**
     * Total
     */
    public TaskStatusesEnvelopeBuilder total(Integer total) {
        taskStatusesEnvelope.setTotal(total);
        return this;
    }

    /**
     * Task statuses
     */
    public TaskStatusesEnvelopeBuilder data(TaskStatuses data) {
        taskStatusesEnvelope.setData(data);
        return this;
    }

    /**
     * Offset
     */
    public TaskStatusesEnvelopeBuilder offset(Integer offset) {
        taskStatusesEnvelope.setOffset(offset);
        return this;
    }

    /**
     * Count
     */
    public TaskStatusesEnvelopeBuilder count(Integer count) {
        taskStatusesEnvelope.setCount(count);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskStatusesEnvelope build() {
        return taskStatusesEnvelope;
    }
}