/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskParameters 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5686835498377628939L;
    private Integer expiresAfter;
    private Long scheduledOn;
    private UpdateParameters update;
    private String value;
    /** GETTER
     * Expire time in seconds
     */
    @JsonGetter("expiresAfter")
    public Integer getExpiresAfter ( ) { 
        return this.expiresAfter;
    }
    
    /** SETTER
     * Expire time in seconds
     */
    @JsonSetter("expiresAfter")
    public void setExpiresAfter (Integer value) { 
        this.expiresAfter = value;
    }
 
    /** GETTER
     * Future scheduled time
     */
    @JsonGetter("scheduledOn")
    public Long getScheduledOn ( ) { 
        return this.scheduledOn;
    }
    
    /** SETTER
     * Future scheduled time
     */
    @JsonSetter("scheduledOn")
    public void setScheduledOn (Long value) { 
        this.scheduledOn = value;
    }
 
    /** GETTER
     * Update parameters
     */
    @JsonGetter("update")
    public UpdateParameters getUpdate ( ) { 
        return this.update;
    }
    
    /** SETTER
     * Update parameters
     */
    @JsonSetter("update")
    public void setUpdate (UpdateParameters value) { 
        this.update = value;
    }
 
    /** GETTER
     * Value to write
     */
    @JsonGetter("value")
    public String getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * Value to write
     */
    @JsonSetter("value")
    public void setValue (String value) { 
        this.value = value;
    }
 
}
 