/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskStatusCounts 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5321367061080533611L;
    private Integer numFailed;
    private Integer numCancelled;
    private Integer totalDevices;
    private Integer numCompleted;
    private Integer numSucceeded;
    /** GETTER
     * Number failed
     */
    @JsonGetter("numFailed")
    public Integer getNumFailed ( ) { 
        return this.numFailed;
    }
    
    /** SETTER
     * Number failed
     */
    @JsonSetter("numFailed")
    public void setNumFailed (Integer value) { 
        this.numFailed = value;
    }
 
    /** GETTER
     * Number cancelled
     */
    @JsonGetter("numCancelled")
    public Integer getNumCancelled ( ) { 
        return this.numCancelled;
    }
    
    /** SETTER
     * Number cancelled
     */
    @JsonSetter("numCancelled")
    public void setNumCancelled (Integer value) { 
        this.numCancelled = value;
    }
 
    /** GETTER
     * Total devices
     */
    @JsonGetter("totalDevices")
    public Integer getTotalDevices ( ) { 
        return this.totalDevices;
    }
    
    /** SETTER
     * Total devices
     */
    @JsonSetter("totalDevices")
    public void setTotalDevices (Integer value) { 
        this.totalDevices = value;
    }
 
    /** GETTER
     * Number completed
     */
    @JsonGetter("numCompleted")
    public Integer getNumCompleted ( ) { 
        return this.numCompleted;
    }
    
    /** SETTER
     * Number completed
     */
    @JsonSetter("numCompleted")
    public void setNumCompleted (Integer value) { 
        this.numCompleted = value;
    }
 
    /** GETTER
     * Number succeeded
     */
    @JsonGetter("numSucceeded")
    public Integer getNumSucceeded ( ) { 
        return this.numSucceeded;
    }
    
    /** SETTER
     * Number succeeded
     */
    @JsonSetter("numSucceeded")
    public void setNumSucceeded (Integer value) { 
        this.numSucceeded = value;
    }
 
}
 