/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskUpdateResponseBuilder {
    //the instance to build
    private TaskUpdateResponse taskUpdateResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TaskUpdateResponseBuilder() {
        taskUpdateResponse = new TaskUpdateResponse();
    }

    /**
     * Task
     */
    public TaskUpdateResponseBuilder data(Task data) {
        taskUpdateResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskUpdateResponse build() {
        return taskUpdateResponse;
    }
}