/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TaskByDidBuilder {
    //the instance to build
    private TaskByDid taskByDid;

    /**
     * Default constructor to initialize the instance
     */
    public TaskByDidBuilder() {
        taskByDid = new TaskByDid();
    }

    /**
     * Filter
     */
    public TaskByDidBuilder filter(String filter) {
        taskByDid.setFilter(filter);
        return this;
    }

    /**
     * Task type
     */
    public TaskByDidBuilder taskType(String taskType) {
        taskByDid.setTaskType(taskType);
        return this;
    }

    /**
     * Modified on
     */
    public TaskByDidBuilder modifiedOn(Long modifiedOn) {
        taskByDid.setModifiedOn(modifiedOn);
        return this;
    }

    /**
     * Device Type ID
     */
    public TaskByDidBuilder dtid(String dtid) {
        taskByDid.setDtid(dtid);
        return this;
    }

    /**
     * Status counts
     */
    public TaskByDidBuilder statusCounts(TaskStatusCounts statusCounts) {
        taskByDid.setStatusCounts(statusCounts);
        return this;
    }

    /**
     * Property
     */
    public TaskByDidBuilder property(String property) {
        taskByDid.setProperty(property);
        return this;
    }

    /**
     * Last known device task status for the specified did
     */
    public TaskByDidBuilder statuses(List<DeviceTask> statuses) {
        taskByDid.setStatuses(statuses);
        return this;
    }

    /**
     * Task ID
     */
    public TaskByDidBuilder id(String id) {
        taskByDid.setId(id);
        return this;
    }

    /**
     * Device IDs
     */
    public TaskByDidBuilder dids(List<String> dids) {
        taskByDid.setDids(dids);
        return this;
    }

    /**
     * Task parameters
     */
    public TaskByDidBuilder taskParameters(TaskParameters taskParameters) {
        taskByDid.setTaskParameters(taskParameters);
        return this;
    }

    /**
     * Created on
     */
    public TaskByDidBuilder createdOn(Long createdOn) {
        taskByDid.setCreatedOn(createdOn);
        return this;
    }

    /**
     * Status
     */
    public TaskByDidBuilder status(String status) {
        taskByDid.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskByDid build() {
        return taskByDid;
    }
}