/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskStatus 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4801425957942432485L;
    private Integer numAttempts;
    private String errorMessage;
    private String errorCode;
    private String did;
    private String status;
    private Long ts;
    /** GETTER
     * Number of attempts
     */
    @JsonGetter("numAttempts")
    public Integer getNumAttempts ( ) { 
        return this.numAttempts;
    }
    
    /** SETTER
     * Number of attempts
     */
    @JsonSetter("numAttempts")
    public void setNumAttempts (Integer value) { 
        this.numAttempts = value;
    }
 
    /** GETTER
     * Error Message
     */
    @JsonGetter("errorMessage")
    public String getErrorMessage ( ) { 
        return this.errorMessage;
    }
    
    /** SETTER
     * Error Message
     */
    @JsonSetter("errorMessage")
    public void setErrorMessage (String value) { 
        this.errorMessage = value;
    }
 
    /** GETTER
     * Error Code
     */
    @JsonGetter("errorCode")
    public String getErrorCode ( ) { 
        return this.errorCode;
    }
    
    /** SETTER
     * Error Code
     */
    @JsonSetter("errorCode")
    public void setErrorCode (String value) { 
        this.errorCode = value;
    }
 
    /** GETTER
     * Device ID
     */
    @JsonGetter("did")
    public String getDid ( ) { 
        return this.did;
    }
    
    /** SETTER
     * Device ID
     */
    @JsonSetter("did")
    public void setDid (String value) { 
        this.did = value;
    }
 
    /** GETTER
     * Status
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * Status
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * Timestamp of most recent status change
     */
    @JsonGetter("ts")
    public Long getTs ( ) { 
        return this.ts;
    }
    
    /** SETTER
     * Timestamp of most recent status change
     */
    @JsonSetter("ts")
    public void setTs (Long value) { 
        this.ts = value;
    }
 
}
 