/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskList 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4692087481688829865L;
    private List<Task> tasks;
    /** GETTER
     * Task list
     */
    @JsonGetter("tasks")
    public List<Task> getTasks ( ) { 
        return this.tasks;
    }
    
    /** SETTER
     * Task list
     */
    @JsonSetter("tasks")
    public void setTasks (List<Task> value) { 
        this.tasks = value;
    }
 
}
 