/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TaskListEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5078281651092550785L;
    private Integer total;
    private TaskList data;
    private TasksStatusCounts statusCounts;
    private Integer offset;
    private Integer count;
    /** GETTER
     * Total
     */
    @JsonGetter("total")
    public Integer getTotal ( ) { 
        return this.total;
    }
    
    /** SETTER
     * Total
     */
    @JsonSetter("total")
    public void setTotal (Integer value) { 
        this.total = value;
    }
 
    /** GETTER
     * Envelope for task list
     */
    @JsonGetter("data")
    public TaskList getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * Envelope for task list
     */
    @JsonSetter("data")
    public void setData (TaskList value) { 
        this.data = value;
    }
 
    /** GETTER
     * Status counts
     */
    @JsonGetter("statusCounts")
    public TasksStatusCounts getStatusCounts ( ) { 
        return this.statusCounts;
    }
    
    /** SETTER
     * Status counts
     */
    @JsonSetter("statusCounts")
    public void setStatusCounts (TasksStatusCounts value) { 
        this.statusCounts = value;
    }
 
    /** GETTER
     * Offset
     */
    @JsonGetter("offset")
    public Integer getOffset ( ) { 
        return this.offset;
    }
    
    /** SETTER
     * Offset
     */
    @JsonSetter("offset")
    public void setOffset (Integer value) { 
        this.offset = value;
    }
 
    /** GETTER
     * Count
     */
    @JsonGetter("count")
    public Integer getCount ( ) { 
        return this.count;
    }
    
    /** SETTER
     * Count
     */
    @JsonSetter("count")
    public void setCount (Integer value) { 
        this.count = value;
    }
 
}
 