/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TokenInfo 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4667815001068056472L;
    private String clientId;
    private String deviceId;
    private Integer expiresIn;
    private String userId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("client_id")
    public String getClientId ( ) { 
        return this.clientId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("client_id")
    public void setClientId (String value) { 
        this.clientId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("device_id")
    public String getDeviceId ( ) { 
        return this.deviceId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("device_id")
    public void setDeviceId (String value) { 
        this.deviceId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expires_in")
    public Integer getExpiresIn ( ) { 
        return this.expiresIn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expires_in")
    public void setExpiresIn (Integer value) { 
        this.expiresIn = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("user_id")
    public String getUserId ( ) { 
        return this.userId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("user_id")
    public void setUserId (String value) { 
        this.userId = value;
    }
 
}
 