/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TokenBuilder {
    //the instance to build
    private Token token;

    /**
     * Default constructor to initialize the instance
     */
    public TokenBuilder() {
        token = new Token();
    }

    public TokenBuilder accessToken(String accessToken) {
        token.setAccessToken(accessToken);
        return this;
    }

    public TokenBuilder expiresIn(Long expiresIn) {
        token.setExpiresIn(expiresIn);
        return this;
    }

    public TokenBuilder scope(String scope) {
        token.setScope(scope);
        return this;
    }

    public TokenBuilder tokenType(String tokenType) {
        token.setTokenType(tokenType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Token build() {
        return token;
    }
}