/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TokenRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5299650239940016845L;
    private String token;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("token")
    public String getToken ( ) { 
        return this.token;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("token")
    public void setToken (String value) { 
        this.token = value;
    }
 
}
 