/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TokenInfoSuccessResponseBuilder {
    //the instance to build
    private TokenInfoSuccessResponse tokenInfoSuccessResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TokenInfoSuccessResponseBuilder() {
        tokenInfoSuccessResponse = new TokenInfoSuccessResponse();
    }

    public TokenInfoSuccessResponseBuilder data(TokenInfo data) {
        tokenInfoSuccessResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TokenInfoSuccessResponse build() {
        return tokenInfoSuccessResponse;
    }
}