/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class TokenResponseBuilder {
    //the instance to build
    private TokenResponse tokenResponse;

    /**
     * Default constructor to initialize the instance
     */
    public TokenResponseBuilder() {
        tokenResponse = new TokenResponse();
    }

    public TokenResponseBuilder data(Token data) {
        tokenResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TokenResponse build() {
        return tokenResponse;
    }
}