/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class UnregisterDeviceResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5407610116650890597L;
    private String certificateInfo;
    private String certificateSignature;
    private Long createdOn;
    private String dtid;
    private String eid;
    private String id;
    private Long manifestVersion;
    private String manifestVersionPolicy;
    private String name;
    private Boolean needProviderAuth;
    private String uid;
    /** GETTER
     * Device certificate information.
     */
    @JsonGetter("certificateInfo")
    public String getCertificateInfo ( ) { 
        return this.certificateInfo;
    }
    
    /** SETTER
     * Device certificate information.
     */
    @JsonSetter("certificateInfo")
    public void setCertificateInfo (String value) { 
        this.certificateInfo = value;
    }
 
    /** GETTER
     * Certificate's signature.
     */
    @JsonGetter("certificateSignature")
    public String getCertificateSignature ( ) { 
        return this.certificateSignature;
    }
    
    /** SETTER
     * Certificate's signature.
     */
    @JsonSetter("certificateSignature")
    public void setCertificateSignature (String value) { 
        this.certificateSignature = value;
    }
 
    /** GETTER
     * Device created on date.
     */
    @JsonGetter("createdOn")
    public Long getCreatedOn ( ) { 
        return this.createdOn;
    }
    
    /** SETTER
     * Device created on date.
     */
    @JsonSetter("createdOn")
    public void setCreatedOn (Long value) { 
        this.createdOn = value;
    }
 
    /** GETTER
     * Device type id.
     */
    @JsonGetter("dtid")
    public String getDtid ( ) { 
        return this.dtid;
    }
    
    /** SETTER
     * Device type id.
     */
    @JsonSetter("dtid")
    public void setDtid (String value) { 
        this.dtid = value;
    }
 
    /** GETTER
     * External ID of the device.
     */
    @JsonGetter("eid")
    public String getEid ( ) { 
        return this.eid;
    }
    
    /** SETTER
     * External ID of the device.
     */
    @JsonSetter("eid")
    public void setEid (String value) { 
        this.eid = value;
    }
 
    /** GETTER
     * Device id.
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * Device id.
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * Device manifest version.
     */
    @JsonGetter("manifestVersion")
    public Long getManifestVersion ( ) { 
        return this.manifestVersion;
    }
    
    /** SETTER
     * Device manifest version.
     */
    @JsonSetter("manifestVersion")
    public void setManifestVersion (Long value) { 
        this.manifestVersion = value;
    }
 
    /** GETTER
     * Device manifest version policy.
     */
    @JsonGetter("manifestVersionPolicy")
    public String getManifestVersionPolicy ( ) { 
        return this.manifestVersionPolicy;
    }
    
    /** SETTER
     * Device manifest version policy.
     */
    @JsonSetter("manifestVersionPolicy")
    public void setManifestVersionPolicy (String value) { 
        this.manifestVersionPolicy = value;
    }
 
    /** GETTER
     * Device name.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Device name.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Device need provider auth.
     */
    @JsonGetter("needProviderAuth")
    public Boolean getNeedProviderAuth ( ) { 
        return this.needProviderAuth;
    }
    
    /** SETTER
     * Device need provider auth.
     */
    @JsonSetter("needProviderAuth")
    public void setNeedProviderAuth (Boolean value) { 
        this.needProviderAuth = value;
    }
 
    /** GETTER
     * User id.
     */
    @JsonGetter("uid")
    public String getUid ( ) { 
        return this.uid;
    }
    
    /** SETTER
     * User id.
     */
    @JsonSetter("uid")
    public void setUid (String value) { 
        this.uid = value;
    }
 
}
 