/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class UpdateParameters 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4797247667428613307L;
    private String updateId;
    /** GETTER
     * Update ID
     */
    @JsonGetter("updateId")
    public String getUpdateId ( ) { 
        return this.updateId;
    }
    
    /** SETTER
     * Update ID
     */
    @JsonSetter("updateId")
    public void setUpdateId (String value) { 
        this.updateId = value;
    }
 
}
 