/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class UpdateParametersBuilder {
    //the instance to build
    private UpdateParameters updateParameters;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateParametersBuilder() {
        updateParameters = new UpdateParameters();
    }

    /**
     * Update ID
     */
    public UpdateParametersBuilder updateId(String updateId) {
        updateParameters.setUpdateId(updateId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateParameters build() {
        return updateParameters;
    }
}