/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class UserEnvelope 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4899114051667474929L;
    private User data;
    /** GETTER
     * User Information
     */
    @JsonGetter("data")
    public User getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * User Information
     */
    @JsonSetter("data")
    public void setData (User value) { 
        this.data = value;
    }
 
}
 