/*
 * ARTIKCloudAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package cloud.artik.api.models;

import java.util.*;

public class ValidationCallbackInfoBuilder {
    //the instance to build
    private ValidationCallbackInfo validationCallbackInfo;

    /**
     * Default constructor to initialize the instance
     */
    public ValidationCallbackInfoBuilder() {
        validationCallbackInfo = new ValidationCallbackInfo();
    }

    /**
     * Application id that created the subscription.
     */
    public ValidationCallbackInfoBuilder aid(String aid) {
        validationCallbackInfo.setAid(aid);
        return this;
    }

    /**
     * Nonce obtained from the validation request.
     */
    public ValidationCallbackInfoBuilder nonce(String nonce) {
        validationCallbackInfo.setNonce(nonce);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ValidationCallbackInfo build() {
        return validationCallbackInfo;
    }
}